require 'rake'
load 'lib/tasks/analytics.rake'

class AnalyticsTaskTest < ActiveSupport::TestCase

  @@monitorees = Patient.all

  def verify_monitoree_count(monitoree_count, active_monitoring, category_type, category, risk_level, count)
    assert_equal(active_monitoring, monitoree_count.active_monitoring)
    assert_equal(category_type, monitoree_count.category_type)
    assert_equal(category, monitoree_count.category)
    assert_equal(risk_level, monitoree_count.risk_level)
    assert_equal(count, monitoree_count.total)
  end

  test "monitoree counts by total" do
    active_counts = monitoree_counts_by_total(@@monitorees, true)
    verify_monitoree_count(active_counts[0], true, 'Overall Total', 'Total', 'High', 3)
    verify_monitoree_count(active_counts[1], true, 'Overall Total', 'Total', 'Low', 2)
    verify_monitoree_count(active_counts[2], true, 'Overall Total', 'Total', 'Medium', 4)
    verify_monitoree_count(active_counts[3], true, 'Overall Total', 'Total', 'No Identified Risk', 4)
    verify_monitoree_count(active_counts[4], true, 'Overall Total', 'Total', 'Missing', 4)
    assert_equal(5, active_counts.length)
    overall_counts = monitoree_counts_by_total(@@monitorees, false)
    verify_monitoree_count(overall_counts[0], false, 'Overall Total', 'Total', 'High', 3)
    verify_monitoree_count(overall_counts[1], false, 'Overall Total', 'Total', 'Low', 4)
    verify_monitoree_count(overall_counts[2], false, 'Overall Total', 'Total', 'Medium', 5)
    verify_monitoree_count(overall_counts[3], false, 'Overall Total', 'Total', 'No Identified Risk', 4)
    verify_monitoree_count(overall_counts[4], false, 'Overall Total', 'Total', 'Missing', 4)
    assert_equal(5, overall_counts.length)
  end

  test "monitoree counts by monitoring status" do
    active_counts = monitoree_counts_by_monitoring_status(@@monitorees)
    verify_monitoree_count(active_counts[0], true, 'Monitoring Status', 'Symptomatic', 'Missing', 1)
    verify_monitoree_count(active_counts[1], true, 'Monitoring Status', 'Non-Reporting', 'Low', 1)
    verify_monitoree_count(active_counts[2], true, 'Monitoring Status', 'Non-Reporting', 'Medium', 2)
    verify_monitoree_count(active_counts[3], true, 'Monitoring Status', 'Non-Reporting', 'Missing', 2)
    verify_monitoree_count(active_counts[4], true, 'Monitoring Status', 'Asymptomatic', 'High', 3)
    verify_monitoree_count(active_counts[5], true, 'Monitoring Status', 'Asymptomatic', 'Low', 1)
    verify_monitoree_count(active_counts[6], true, 'Monitoring Status', 'Asymptomatic', 'Medium', 2)
    verify_monitoree_count(active_counts[7], true, 'Monitoring Status', 'Asymptomatic', 'No Identified Risk', 4)
    assert_equal(9, active_counts.length)
  end

  test "monitoree counts by age group" do
    active_counts = monitoree_counts_by_age_group(@@monitorees, true)
    verify_monitoree_count(active_counts[0], true, 'Age Group', '0-19', 'High', 1)
    verify_monitoree_count(active_counts[1], true, 'Age Group', '0-19', 'Low', 1)
    verify_monitoree_count(active_counts[2], true, 'Age Group', '0-19', 'Medium', 2)
    verify_monitoree_count(active_counts[3], true, 'Age Group', '0-19', 'No Identified Risk', 2)
    verify_monitoree_count(active_counts[4], true, 'Age Group', '0-19', 'Missing', 1)
    verify_monitoree_count(active_counts[5], true, 'Age Group', '20-29', 'Missing', 2)
    verify_monitoree_count(active_counts[6], true, 'Age Group', '30-39', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[7], true, 'Age Group', '40-49', 'High', 1)
    verify_monitoree_count(active_counts[8], true, 'Age Group', '40-49', 'Low', 1)
    verify_monitoree_count(active_counts[9], true, 'Age Group', '40-49', 'Medium', 1)
    verify_monitoree_count(active_counts[10], true, 'Age Group', '40-49', 'Missing', 1)
    verify_monitoree_count(active_counts[11], true, 'Age Group', '50-59', 'High', 1)
    verify_monitoree_count(active_counts[12], true, 'Age Group', '60-69', 'Medium', 1)
    verify_monitoree_count(active_counts[13], true, 'Age Group', '>=80', 'No Identified Risk', 1)
    assert_equal(14, active_counts.length)
    overall_counts = monitoree_counts_by_age_group(@@monitorees, false)
    verify_monitoree_count(overall_counts[0], false, 'Age Group', '0-19', 'High', 1)
    verify_monitoree_count(overall_counts[1], false, 'Age Group', '0-19', 'Low', 1)
    verify_monitoree_count(overall_counts[2], false, 'Age Group', '0-19', 'Medium', 3)
    verify_monitoree_count(overall_counts[3], false, 'Age Group', '0-19', 'No Identified Risk', 2)
    verify_monitoree_count(overall_counts[4], false, 'Age Group', '0-19', 'Missing', 1)
    verify_monitoree_count(overall_counts[5], false, 'Age Group', '20-29', 'Missing', 2)
    verify_monitoree_count(overall_counts[6], false, 'Age Group', '30-39', 'Low', 1)
    verify_monitoree_count(overall_counts[7], false, 'Age Group', '30-39', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[8], false, 'Age Group', '40-49', 'High', 1)
    verify_monitoree_count(overall_counts[9], false, 'Age Group', '40-49', 'Low', 1)
    verify_monitoree_count(overall_counts[10], false, 'Age Group', '40-49', 'Medium', 1)
    verify_monitoree_count(overall_counts[11], false, 'Age Group', '40-49', 'Missing', 1)
    verify_monitoree_count(overall_counts[12], false, 'Age Group', '50-59', 'High', 1)
    verify_monitoree_count(overall_counts[13], false, 'Age Group', '60-69', 'Low', 1)
    verify_monitoree_count(overall_counts[14], false, 'Age Group', '60-69', 'Medium', 1)
    verify_monitoree_count(overall_counts[15], false, 'Age Group', '>=80', 'No Identified Risk', 1)
    assert_equal(16, overall_counts.length)
  end

  test "monitoree counts by sex" do
    active_counts = monitoree_counts_by_sex(@@monitorees, true)
    verify_monitoree_count(active_counts[0], true, 'Sex', 'Female', 'High', 1)
    verify_monitoree_count(active_counts[1], true, 'Sex', 'Female', 'Low', 1)
    verify_monitoree_count(active_counts[2], true, 'Sex', 'Female', 'Medium', 1)
    verify_monitoree_count(active_counts[3], true, 'Sex', 'Female', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[4], true, 'Sex', 'Female', 'Missing', 2)
    verify_monitoree_count(active_counts[5], true, 'Sex', 'Male', 'High', 1)
    verify_monitoree_count(active_counts[6], true, 'Sex', 'Male', 'Low', 1)
    verify_monitoree_count(active_counts[7], true, 'Sex', 'Male', 'Medium', 1)
    verify_monitoree_count(active_counts[8], true, 'Sex', 'Male', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[9], true, 'Sex', 'Male', 'Missing', 2)
    verify_monitoree_count(active_counts[10], true, 'Sex', 'Unknown', 'High', 1)
    verify_monitoree_count(active_counts[11], true, 'Sex', 'Unknown', 'Medium', 1)
    verify_monitoree_count(active_counts[12], true, 'Sex', 'Unknown', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[13], true, 'Sex', 'Missing', 'Medium', 1)
    verify_monitoree_count(active_counts[14], true, 'Sex', 'Missing', 'No Identified Risk', 1)
    assert_equal(15, active_counts.length)
    overall_counts = monitoree_counts_by_sex(@@monitorees, false)
    verify_monitoree_count(overall_counts[0], false, 'Sex', 'Female', 'High', 1)
    verify_monitoree_count(overall_counts[1], false, 'Sex', 'Female', 'Low', 2)
    verify_monitoree_count(overall_counts[2], false, 'Sex', 'Female', 'Medium', 1)
    verify_monitoree_count(overall_counts[3], false, 'Sex', 'Female', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[4], false, 'Sex', 'Female', 'Missing', 2)
    verify_monitoree_count(overall_counts[5], false, 'Sex', 'Male', 'High', 1)
    verify_monitoree_count(overall_counts[6], false, 'Sex', 'Male', 'Low', 1)
    verify_monitoree_count(overall_counts[7], false, 'Sex', 'Male', 'Medium', 1)
    verify_monitoree_count(overall_counts[8], false, 'Sex', 'Male', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[9], false, 'Sex', 'Male', 'Missing', 2)
    verify_monitoree_count(overall_counts[10], false, 'Sex', 'Unknown', 'High', 1)
    verify_monitoree_count(overall_counts[11], false, 'Sex', 'Unknown', 'Low', 1)
    verify_monitoree_count(overall_counts[12], false, 'Sex', 'Unknown', 'Medium', 2)
    verify_monitoree_count(overall_counts[13], false, 'Sex', 'Unknown', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[14], false, 'Sex', 'Missing', 'Medium', 1)
    verify_monitoree_count(overall_counts[15], false, 'Sex', 'Missing', 'No Identified Risk', 1)
    assert_equal(16, overall_counts.length)
  end

  test "monitoree counts by risk factor" do
    active_counts = monitoree_counts_by_risk_factor(@@monitorees, true)
    verify_monitoree_count(active_counts[0], true, 'Risk Factor', 'Close Contact with Known Case', 'High', 1)
    verify_monitoree_count(active_counts[1], true, 'Risk Factor', 'Close Contact with Known Case', 'Medium', 1)
    verify_monitoree_count(active_counts[2], true, 'Risk Factor', 'Travel to Affected Country or Area', 'High', 2)
    verify_monitoree_count(active_counts[3], true, 'Risk Factor', 'Travel to Affected Country or Area', 'Medium', 2)
    verify_monitoree_count(active_counts[4], true, 'Risk Factor', 'Travel to Affected Country or Area', 'No Identified Risk', 2)
    verify_monitoree_count(active_counts[5], true, 'Risk Factor', 'Travel to Affected Country or Area', 'Missing', 1)
    verify_monitoree_count(active_counts[6], true, 'Risk Factor', 'Was in Healthcare Facility with Known Cases', 'High', 2)
    verify_monitoree_count(active_counts[7], true, 'Risk Factor', 'Was in Healthcare Facility with Known Cases', 'Medium', 1)
    verify_monitoree_count(active_counts[8], true, 'Risk Factor', 'Was in Healthcare Facility with Known Cases', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[9], true, 'Risk Factor', 'Was in Healthcare Facility with Known Cases', 'Missing', 1)
    verify_monitoree_count(active_counts[10], true, 'Risk Factor', 'Common Exposure Cohort', 'High', 2)
    verify_monitoree_count(active_counts[11], true, 'Risk Factor', 'Crew on Passenger or Cargo Flight', 'High', 2)
    verify_monitoree_count(active_counts[12], true, 'Risk Factor', 'Crew on Passenger or Cargo Flight', 'Medium', 1)
    verify_monitoree_count(active_counts[13], true, 'Risk Factor', 'Crew on Passenger or Cargo Flight', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[14], true, 'Risk Factor', 'Laboratory Personnel', 'Medium', 1)
    verify_monitoree_count(active_counts[15], true, 'Risk Factor', 'Laboratory Personnel', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[16], true, 'Risk Factor', 'Total', 'High', 3)
    verify_monitoree_count(active_counts[17], true, 'Risk Factor', 'Total', 'Medium', 2)
    verify_monitoree_count(active_counts[18], true, 'Risk Factor', 'Total', 'No Identified Risk', 2)
    verify_monitoree_count(active_counts[19], true, 'Risk Factor', 'Total', 'Missing', 2)
    assert_equal(20, active_counts.length)
    overall_counts = monitoree_counts_by_risk_factor(@@monitorees, false)
    verify_monitoree_count(overall_counts[0], false, 'Risk Factor', 'Close Contact with Known Case', 'High', 1)
    verify_monitoree_count(overall_counts[1], false, 'Risk Factor', 'Close Contact with Known Case', 'Low', 1)
    verify_monitoree_count(overall_counts[2], false, 'Risk Factor', 'Close Contact with Known Case', 'Medium', 1)
    verify_monitoree_count(overall_counts[3], false, 'Risk Factor', 'Travel to Affected Country or Area', 'High', 2)
    verify_monitoree_count(overall_counts[4], false, 'Risk Factor', 'Travel to Affected Country or Area', 'Low', 2)
    verify_monitoree_count(overall_counts[5], false, 'Risk Factor', 'Travel to Affected Country or Area', 'Medium', 2)
    verify_monitoree_count(overall_counts[6], false, 'Risk Factor', 'Travel to Affected Country or Area', 'No Identified Risk', 2)
    verify_monitoree_count(overall_counts[7], false, 'Risk Factor', 'Travel to Affected Country or Area', 'Missing', 1)
    verify_monitoree_count(overall_counts[8], false, 'Risk Factor', 'Was in Healthcare Facility with Known Cases', 'High', 2)
    verify_monitoree_count(overall_counts[9], false, 'Risk Factor', 'Was in Healthcare Facility with Known Cases', 'Low', 1)
    verify_monitoree_count(overall_counts[10], false, 'Risk Factor', 'Was in Healthcare Facility with Known Cases', 'Medium', 1)
    verify_monitoree_count(overall_counts[11], false, 'Risk Factor', 'Was in Healthcare Facility with Known Cases', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[12], false, 'Risk Factor', 'Was in Healthcare Facility with Known Cases', 'Missing', 1)
    verify_monitoree_count(overall_counts[13], false, 'Risk Factor', 'Healthcare Personnel', 'Low', 1)
    verify_monitoree_count(overall_counts[14], false, 'Risk Factor', 'Common Exposure Cohort', 'High', 2)
    verify_monitoree_count(overall_counts[15], false, 'Risk Factor', 'Crew on Passenger or Cargo Flight', 'High', 2)
    verify_monitoree_count(overall_counts[16], false, 'Risk Factor', 'Crew on Passenger or Cargo Flight', 'Low', 1)
    verify_monitoree_count(overall_counts[17], false, 'Risk Factor', 'Crew on Passenger or Cargo Flight', 'Medium', 1)
    verify_monitoree_count(overall_counts[18], false, 'Risk Factor', 'Crew on Passenger or Cargo Flight', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[19], false, 'Risk Factor', 'Laboratory Personnel', 'Low', 1)
    verify_monitoree_count(overall_counts[20], false, 'Risk Factor', 'Laboratory Personnel', 'Medium', 1)
    verify_monitoree_count(overall_counts[21], false, 'Risk Factor', 'Laboratory Personnel', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[22], false, 'Risk Factor', 'Total', 'High', 3)
    verify_monitoree_count(overall_counts[23], false, 'Risk Factor', 'Total', 'Low', 2)
    verify_monitoree_count(overall_counts[24], false, 'Risk Factor', 'Total', 'Medium', 2)
    verify_monitoree_count(overall_counts[25], false, 'Risk Factor', 'Total', 'No Identified Risk', 2)
    verify_monitoree_count(overall_counts[26], false, 'Risk Factor', 'Total', 'Missing', 2)
    assert_equal(27, overall_counts.length)
  end

  test "monitoree counts by exposure country" do
    active_counts = monitoree_counts_by_exposure_country(@@monitorees, true)
    verify_monitoree_count(active_counts[0], true, 'Exposure Country', 'China', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[1], true, 'Exposure Country', 'Faroe Islands', 'High', 1)
    verify_monitoree_count(active_counts[2], true, 'Exposure Country', 'Faroe Islands', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[3], true, 'Exposure Country', 'Iceland', 'High', 1)
    verify_monitoree_count(active_counts[4], true, 'Exposure Country', 'Korea', 'Medium', 1)
    verify_monitoree_count(active_counts[5], true, 'Exposure Country', 'Malaysia', 'High', 1)
    verify_monitoree_count(active_counts[6], true, 'Exposure Country', 'Malaysia', 'Medium', 1)
    verify_monitoree_count(active_counts[7], true, 'Exposure Country', 'Malaysia', 'Missing', 1)
    verify_monitoree_count(active_counts[8], true, 'Exposure Country', 'United States Minor Outlying Islands', 'Missing', 1)
    verify_monitoree_count(active_counts[9], true, 'Exposure Country', 'Total', 'High', 3)
    verify_monitoree_count(active_counts[10], true, 'Exposure Country', 'Total', 'Medium', 2)
    verify_monitoree_count(active_counts[11], true, 'Exposure Country', 'Total', 'No Identified Risk', 2)
    verify_monitoree_count(active_counts[12], true, 'Exposure Country', 'Total', 'Missing', 2)
    assert_equal(13, active_counts.length)
    overall_counts = monitoree_counts_by_exposure_country(@@monitorees, false)
    verify_monitoree_count(overall_counts[0], false, 'Exposure Country', 'Brazil', 'Low', 1)
    verify_monitoree_count(overall_counts[1], false, 'Exposure Country', 'China', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[2], false, 'Exposure Country', 'Faroe Islands', 'High', 1)
    verify_monitoree_count(overall_counts[3], false, 'Exposure Country', 'Faroe Islands', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[4], false, 'Exposure Country', 'Iceland', 'High', 1)
    verify_monitoree_count(overall_counts[5], false, 'Exposure Country', 'Korea', 'Medium', 1)
    verify_monitoree_count(overall_counts[6], false, 'Exposure Country', 'Malaysia', 'High', 1)
    verify_monitoree_count(overall_counts[7], false, 'Exposure Country', 'Malaysia', 'Low', 1)
    verify_monitoree_count(overall_counts[8], false, 'Exposure Country', 'Malaysia', 'Medium', 1)
    verify_monitoree_count(overall_counts[9], false, 'Exposure Country', 'Malaysia', 'Missing', 1)
    verify_monitoree_count(overall_counts[10], false, 'Exposure Country', 'United States Minor Outlying Islands', 'Missing', 1)
    verify_monitoree_count(overall_counts[11], false, 'Exposure Country', 'Total', 'High', 3)
    verify_monitoree_count(overall_counts[12], false, 'Exposure Country', 'Total', 'Low', 2)
    verify_monitoree_count(overall_counts[13], false, 'Exposure Country', 'Total', 'Medium', 2)
    verify_monitoree_count(overall_counts[14], false, 'Exposure Country', 'Total', 'No Identified Risk', 2)
    verify_monitoree_count(overall_counts[15], false, 'Exposure Country', 'Total', 'Missing', 2)
    assert_equal(16, overall_counts.length)
  end

  test "monitoree counts by last exposure date" do
    active_counts = monitoree_counts_by_last_exposure_date(@@monitorees, true)
    verify_monitoree_count(active_counts[0], true, 'Last Exposure Date', '2020-02-28', 'Missing', 1)
    verify_monitoree_count(active_counts[1], true, 'Last Exposure Date', '2020-02-29', 'Medium', 1)
    verify_monitoree_count(active_counts[2], true, 'Last Exposure Date', '2020-03-01', 'High', 1)
    verify_monitoree_count(active_counts[3], true, 'Last Exposure Date', '2020-03-04', 'Low', 1)
    verify_monitoree_count(active_counts[4], true, 'Last Exposure Date', '2020-03-05', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[5], true, 'Last Exposure Date', '2020-03-25', 'High', 1)
    assert_equal(6, active_counts.length)
    overall_counts = monitoree_counts_by_last_exposure_date(@@monitorees, false)
    verify_monitoree_count(overall_counts[0], false, 'Last Exposure Date', '2020-02-28', 'Missing', 1)
    verify_monitoree_count(overall_counts[1], false, 'Last Exposure Date', '2020-02-29', 'Medium', 1)
    verify_monitoree_count(overall_counts[2], false, 'Last Exposure Date', '2020-03-01', 'High', 1)
    verify_monitoree_count(overall_counts[3], false, 'Last Exposure Date', '2020-03-04', 'Low', 1)
    verify_monitoree_count(overall_counts[4], false, 'Last Exposure Date', '2020-03-05', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[5], false, 'Last Exposure Date', '2020-03-25', 'High', 1)
    assert_equal(6, overall_counts.length)
  end

  test "monitoree counts by last exposure week" do
    active_counts = monitoree_counts_by_last_exposure_week(@@monitorees, true)
    verify_monitoree_count(active_counts[0], true, 'Last Exposure Week', '2019-09-29', 'Medium', 1)
    verify_monitoree_count(active_counts[1], true, 'Last Exposure Week', '2019-11-10', 'High', 1)
    verify_monitoree_count(active_counts[2], true, 'Last Exposure Week', '2019-12-29', 'Medium', 1)
    verify_monitoree_count(active_counts[3], true, 'Last Exposure Week', '2019-12-29', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[4], true, 'Last Exposure Week', '2020-02-02', 'Missing', 2)
    verify_monitoree_count(active_counts[5], true, 'Last Exposure Week', '2020-02-09', 'Low', 1)
    verify_monitoree_count(active_counts[6], true, 'Last Exposure Week', '2020-02-09', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[7], true, 'Last Exposure Week', '2020-02-09', 'Missing', 1)
    verify_monitoree_count(active_counts[8], true, 'Last Exposure Week', '2020-02-16', 'Medium', 1)
    verify_monitoree_count(active_counts[9], true, 'Last Exposure Week', '2020-02-16', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[10], true, 'Last Exposure Week', '2020-02-23', 'High', 1)
    verify_monitoree_count(active_counts[11], true, 'Last Exposure Week', '2020-02-23', 'Medium', 1)
    verify_monitoree_count(active_counts[12], true, 'Last Exposure Week', '2020-02-23', 'Missing', 1)
    verify_monitoree_count(active_counts[13], true, 'Last Exposure Week', '2020-03-01', 'Low', 1)
    verify_monitoree_count(active_counts[14], true, 'Last Exposure Week', '2020-03-01', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[15], true, 'Last Exposure Week', '2020-03-22', 'High', 1)
    assert_equal(16, active_counts.length)
    overall_counts = monitoree_counts_by_last_exposure_week(@@monitorees, false)
    verify_monitoree_count(overall_counts[0], false, 'Last Exposure Week', '2019-05-05', 'Low', 1)
    verify_monitoree_count(overall_counts[1], false, 'Last Exposure Week', '2019-05-12', 'Low', 1)
    verify_monitoree_count(overall_counts[2], false, 'Last Exposure Week', '2019-09-29', 'Medium', 1)
    verify_monitoree_count(overall_counts[3], false, 'Last Exposure Week', '2019-11-10', 'High', 1)
    verify_monitoree_count(overall_counts[4], false, 'Last Exposure Week', '2019-12-29', 'Medium', 1)
    verify_monitoree_count(overall_counts[5], false, 'Last Exposure Week', '2019-12-29', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[6], false, 'Last Exposure Week', '2020-01-19', 'Medium', 1)
    verify_monitoree_count(overall_counts[7], false, 'Last Exposure Week', '2020-02-02', 'Missing', 2)
    verify_monitoree_count(overall_counts[8], false, 'Last Exposure Week', '2020-02-09', 'Low', 1)
    verify_monitoree_count(overall_counts[9], false, 'Last Exposure Week', '2020-02-09', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[10], false, 'Last Exposure Week', '2020-02-09', 'Missing', 1)
    verify_monitoree_count(overall_counts[11], false, 'Last Exposure Week', '2020-02-16', 'Medium', 1)
    verify_monitoree_count(overall_counts[12], false, 'Last Exposure Week', '2020-02-16', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[13], false, 'Last Exposure Week', '2020-02-23', 'High', 1)
    verify_monitoree_count(overall_counts[14], false, 'Last Exposure Week', '2020-02-23', 'Medium', 1)
    verify_monitoree_count(overall_counts[15], false, 'Last Exposure Week', '2020-02-23', 'Missing', 1)
    verify_monitoree_count(overall_counts[16], false, 'Last Exposure Week', '2020-03-01', 'Low', 1)
    verify_monitoree_count(overall_counts[17], false, 'Last Exposure Week', '2020-03-01', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[18], false, 'Last Exposure Week', '2020-03-22', 'High', 1)
    assert_equal(19, overall_counts.length)
  end

  test "monitoree counts by last exposure month" do
    active_counts = monitoree_counts_by_last_exposure_month(@@monitorees, true)
    verify_monitoree_count(active_counts[0], true, 'Last Exposure Month', '2019-09-01', 'Medium', 1)
    verify_monitoree_count(active_counts[1], true, 'Last Exposure Month', '2019-11-01', 'High', 1)
    verify_monitoree_count(active_counts[2], true, 'Last Exposure Month', '2020-01-01', 'Medium', 1)
    verify_monitoree_count(active_counts[3], true, 'Last Exposure Month', '2020-01-01', 'No Identified Risk', 1)
    verify_monitoree_count(active_counts[4], true, 'Last Exposure Month', '2020-02-01', 'Low', 1)
    verify_monitoree_count(active_counts[5], true, 'Last Exposure Month', '2020-02-01', 'Medium', 2)
    verify_monitoree_count(active_counts[6], true, 'Last Exposure Month', '2020-02-01', 'No Identified Risk', 2)
    verify_monitoree_count(active_counts[7], true, 'Last Exposure Month', '2020-02-01', 'Missing', 4)
    verify_monitoree_count(active_counts[8], true, 'Last Exposure Month', '2020-03-01', 'High', 2)
    verify_monitoree_count(active_counts[9], true, 'Last Exposure Month', '2020-03-01', 'Low', 1)
    verify_monitoree_count(active_counts[10], true, 'Last Exposure Month', '2020-03-01', 'No Identified Risk', 1)
    assert_equal(11, active_counts.length)
    overall_counts = monitoree_counts_by_last_exposure_month(@@monitorees, false)
    verify_monitoree_count(overall_counts[0], false, 'Last Exposure Month', '2019-05-01', 'Low', 2)
    verify_monitoree_count(overall_counts[1], false, 'Last Exposure Month', '2019-09-01', 'Medium', 1)
    verify_monitoree_count(overall_counts[2], false, 'Last Exposure Month', '2019-11-01', 'High', 1)
    verify_monitoree_count(overall_counts[3], false, 'Last Exposure Month', '2020-01-01', 'Medium', 2)
    verify_monitoree_count(overall_counts[4], false, 'Last Exposure Month', '2020-01-01', 'No Identified Risk', 1)
    verify_monitoree_count(overall_counts[5], false, 'Last Exposure Month', '2020-02-01', 'Low', 1)
    verify_monitoree_count(overall_counts[6], false, 'Last Exposure Month', '2020-02-01', 'Medium', 2)
    verify_monitoree_count(overall_counts[7], false, 'Last Exposure Month', '2020-02-01', 'No Identified Risk', 2)
    verify_monitoree_count(overall_counts[8], false, 'Last Exposure Month', '2020-02-01', 'Missing', 4)
    verify_monitoree_count(overall_counts[9], false, 'Last Exposure Month', '2020-03-01', 'High', 2)
    verify_monitoree_count(overall_counts[10], false, 'Last Exposure Month', '2020-03-01', 'Low', 1)
    verify_monitoree_count(overall_counts[11], false, 'Last Exposure Month', '2020-03-01', 'No Identified Risk', 1)
    assert_equal(12, overall_counts.length)
  end
end