require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'test/rake/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
Layout/LineLength:
  Max: 160
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 160
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 750
Metrics/ParameterLists:
  Max: 8
Metrics/BlockLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
# Good options that are not enabled by default yet and thus produce warnings
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
# Very good options that are not enabled by default yet and thus produce warnings
Style/ClassVars:
  Enabled: true
  Exclude:
    - test/**/*
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Naming/VariableNumber:
  EnforcedStyle: snake_case
Style/MultilineTernaryOperator:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
Lint/MissingSuper:
  Enabled: true
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Style/StringConcatenation:
  Enabled: false
Style/SingleArgumentDig:
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: true
Style/GlobalStdStream:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: true
Style/SoleNestedConditional:
  Enabled: true
Style/CombinableLoops:
  Enabled: false
Gemspec/DateAssignment: # (new in 1.10)
  Enabled: true
Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/NumberedParameterAssignment: # (new in 1.9)
  Enabled: true
Lint/OrAssignmentToConstant: # (new in 1.9)
  Enabled: true
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true
Lint/SymbolConversion: # (new in 1.9)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/TripleQuotes: # (new in 1.9)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/EndlessMethod: # (new in 1.8)
  Enabled: true
Style/HashConversion: # (new in 1.10)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/IfWithBooleanLiteralBranches: # (new in 1.9)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true
Lint/EmptyInPattern: # (new in 1.16)
  Enabled: true
Style/InPatternThen: # (new in 1.16)
  Enabled: true
Style/MultilineInPatternThen: # (new in 1.16)
  Enabled: true
Style/QuotedSymbols: # (new in 1.16)
  Enabled: true
Style/StringChars: # (new in 1.12)
  Enabled: true
Rails/FilePath:
  Enabled: false
  EnforcedStyle: arguments
Style/SafeNavigation:
  Enabled: false
Rails/WhereNot:
  Enabled: false
Rails/WhereEquals:
  Enabled: false
Rails/ShortI18n:
  Enabled: false
Rails/Pluck:
  Enabled: false
Rails/FindById:
  Enabled: false
Rails/I18nLocaleAssignment:
  Enabled: false
Rails/UnusedIgnoredColumns:
  Enabled: false
Rails/TimeZoneAssignment:
  Enabled: false
Rails/Inquiry:
  Enabled: false
Rails/NegateInclude:
  Enabled: false
Rails/RenderInline:
  Enabled: false
Rails/SquishedSQLHeredocs:
  Enabled: false
Rails/ActiveRecordCallbacksOrder:
  Enabled: false
Rails/AfterCommitOverride:
  Enabled: false
Rails/AddColumnIndex:
  Enabled: false
Rails/RenderPlainText:
  Enabled: false
Rails/MailerName:
  Enabled: false
Rails/ExpandedDateRange:
  Enabled: false
Rails/EagerEvaluationLogMessage:
  Enabled: false
Rails/MatchRoute:
  Enabled: false
Rails/PluckInWhere:
  Enabled: false
Rails/WhereExists:
  Enabled: false
Rails/AttributeDefaultBlockValue:
  Enabled: false
Performance/Sum:
  Enabled: false
Performance/StringInclude:
  Enabled: false
Performance/Squeeze:
  Enabled: false
Performance/SortReverse:
  Enabled: false
Performance/ReverseFirst:
  Enabled: false
Performance/RedundantStringChars:
  Enabled: false
Performance/RedundantSplitRegexpArgument:
  Enabled: false
Performance/MethodObjectAsBlock:
  Enabled: false
Performance/RedundantSortBlock:
  Enabled: false
Performance/MapCompact:
  Enabled: false
Performance/BigDecimalWithNumericArgument:
  Enabled: false
Performance/BlockGivenWithExplicitBlock:
  Enabled: false
Performance/RedundantEqualityComparisonBlock:
  Enabled: false
Performance/CollectionLiteralInLoop:
  Enabled: false
  MinSize: 4
Performance/ConstantRegexp:
  Enabled: false
Performance/AncestorsInclude:
  Enabled: false
Performance/InefficientHashSearch:
  Enabled: false
Rails/Present:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
Rails/Presence:
  Enabled: false
Performance/Casecmp:
  Enabled: false
Rails/Blank:
  Enabled: false
Rails/HttpStatus:
  Enabled: false
Rails/TimeZone:
  Enabled: false
Rails/Date:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Lint/RedundantCopDisableDirective:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Performance/Count:
  Enabled: false
Performance/RangeInclude:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/IndexBy:
  Enabled: false
Rails/IndexWith:
  Enabled: false
Performance/StringReplacement:
  Enabled: false
Performance/ReverseEach:
  Enabled: false
