AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'test/system/**/*'
    - 'test/rake/**/*'
    - 'test/jobs/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
Layout/LineLength:
  Max: 160
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 500
Metrics/BlockLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
# Good options that are not enabled by default yet and thus produce warnings
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
# Very good options that are not enabled by default yet and thus produce warnings
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Naming/VariableNumber:
  EnforcedStyle: snake_case
Style/MultilineTernaryOperator:
  Enabled: false
