# frozen_string_literal: true

class EnrollmentFormSteps < ApplicationSystemTestCase
  # rubocop:disable Layout/LineLength
  def steps
    {
      identification: [
        { id: 'workflow', type: :react_select, required: true },
        { id: 'first_name', type: :text, required: true, info_page: true },
        { id: 'middle_name', type: :text, info_page: true },
        { id: 'last_name', type: :text, required: true, info_page: true },
        { id: 'date_of_birth', type: :date, required: true, info_page: true },
        { id: 'age', type: :age, info_page: true },
        { id: 'sex', type: :select, info_page: true },
        { id: 'gender_identity', type: :select, info_page: true },
        { id: 'sexual_orientation', type: :select, info_page: true },
        { id: 'white', type: :race, info_page: 'White', label: 'WHITE' },
        { id: 'black_or_african_american', type: :race, info_page: 'Black or African American', label: 'BLACK OR AFRICAN AMERICAN' },
        { id: 'american_indian_or_alaska_native', type: :race, info_page: 'American Indian or Alaska Native', label: 'AMERICAN INDIAN OR ALASKA NATIVE' },
        { id: 'asian', type: :race, info_page: 'Asian', label: 'ASIAN' },
        { id: 'native_hawaiian_or_other_pacific_islander', type: :race, info_page: 'Native Hawaiian or Other Pacific Islander', label: 'NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER' },
        { id: 'race_other', type: :race, info_page: 'Other', label: 'OTHER' },
        { id: 'race_unknown', type: :race, info_page: 'Unknown', label: 'UNKNOWN' },
        { id: 'race_refused_to_answer', type: :race, info_page: 'Refused to Answer', label: 'REFUSED TO ANSWER' },
        { id: 'ethnicity', type: :select, info_page: true },
        { id: 'primary_language', type: :react_select, info_page: true },
        { id: 'secondary_language', type: :react_select },
        { id: 'interpretation_required', type: :checkbox, label: 'INTERPRETATION REQUIRED' },
        { id: 'nationality', type: :text, info_page: true },
        { id: 'user_defined_id_statelocal', type: :text, info_page: true },
        { id: 'user_defined_id_cdc', type: :text, info_page: true },
        { id: 'user_defined_id_nndss', type: :text, info_page: true }
      ],
      address: [
        { id: 'address_line_1', type: :text, required: true, info_page: true, tab: 'Home Address Within USA', copiable: true },
        { id: 'address_city', type: :text, required: true, info_page: true, tab: 'Home Address Within USA', copiable: true },
        { id: 'address_state', type: :select, required: true, info_page: true, tab: 'Home Address Within USA', copiable: true },
        { id: 'address_line_2', type: :text, info_page: true, tab: 'Home Address Within USA', copiable: true },
        { id: 'address_zip', type: :text, required: true, info_page: true, tab: 'Home Address Within USA', copiable: true },
        { id: 'address_county', type: :text, info_page: true, tab: 'Home Address Within USA', copiable: true },
        { id: 'monitored_address_line_1', type: :text, info_page: true, tab: 'Home Address Within USA' },
        { id: 'monitored_address_city', type: :text, info_page: true, tab: 'Home Address Within USA' },
        { id: 'monitored_address_state', type: :select, info_page: true, tab: 'Home Address Within USA' },
        { id: 'monitored_address_line_2', type: :text, info_page: true, tab: 'Home Address Within USA' },
        { id: 'monitored_address_zip', type: :text, info_page: true, tab: 'Home Address Within USA' },
        { id: 'monitored_address_county', type: :text, info_page: true, tab: 'Home Address Within USA' },
        { id: 'foreign_address_line_1', type: :text, info_page: true, tab: 'Home Address Outside USA (Foreign)' },
        { id: 'foreign_address_city', type: :text, info_page: true, tab: 'Home Address Outside USA (Foreign)' },
        { id: 'foreign_address_country', type: :select, info_page: true, tab: 'Home Address Outside USA (Foreign)' },
        { id: 'foreign_address_line_2', type: :text, info_page: true, tab: 'Home Address Outside USA (Foreign)' },
        { id: 'foreign_address_zip', type: :text, info_page: true, tab: 'Home Address Outside USA (Foreign)' },
        { id: 'foreign_address_line_3', type: :text, info_page: true, tab: 'Home Address Outside USA (Foreign)' },
        { id: 'foreign_address_state', type: :text, info_page: true, tab: 'Home Address Outside USA (Foreign)' },
        { id: 'foreign_monitored_address_line_1', type: :text, info_page: true, tab: 'Home Address Outside USA (Foreign)' },
        { id: 'foreign_monitored_address_city', type: :text, info_page: true, tab: 'Home Address Outside USA (Foreign)' },
        { id: 'foreign_monitored_address_state', type: :select, info_page: true, tab: 'Home Address Outside USA (Foreign)' },
        { id: 'foreign_monitored_address_line_2', type: :text, info_page: true, tab: 'Home Address Outside USA (Foreign)' },
        { id: 'foreign_monitored_address_zip', type: :text, info_page: true, tab: 'Home Address Outside USA (Foreign)' },
        { id: 'foreign_monitored_address_county', type: :text, info_page: true, tab: 'Home Address Outside USA (Foreign)' }
      ],
      contact_information: [
        { id: 'preferred_contact_method', type: :select, required: true },
        { id: 'preferred_contact_time', type: :select, info_page: true },
        { id: 'primary_telephone', type: :phone, info_page: true },
        { id: 'primary_telephone_type', type: :select, info_page: true },
        { id: 'secondary_telephone', type: :phone },
        { id: 'secondary_telephone_type', type: :select },
        { id: 'email', type: :text, info_page: true },
        { id: 'confirm_email', type: :text }
      ],
      arrival_information: [
        { id: 'port_of_origin', type: :text, info_page: true },
        { id: 'date_of_departure', type: :date, info_page: true },
        { id: 'source_of_report', type: :select },
        { id: 'flight_or_vessel_number', type: :text, info_page: true },
        { id: 'flight_or_vessel_carrier', type: :text, info_page: true },
        { id: 'port_of_entry_into_usa', type: :text, info_page: true },
        { id: 'date_of_arrival', type: :date, info_page: true },
        { id: 'travel_related_notes', type: :text }
      ],
      planned_travel: [
        { id: 'additional_planned_travel_type', type: :select, info_page: true },
        { id: 'additional_planned_travel_destination', type: :text },
        { id: 'additional_planned_travel_destination_state', type: :select, info_page: true },
        { id: 'additional_planned_travel_destination_country', type: :select, info_page: true },
        { id: 'additional_planned_travel_country', type: :select, info_page: true },
        { id: 'additional_planned_travel_port_of_departure', type: :text, info_page: true },
        { id: 'additional_planned_travel_start_date', type: :date, info_page: true },
        { id: 'additional_planned_travel_end_date', type: :date, info_page: true },
        { id: 'additional_planned_travel_related_notes', type: :text }
      ],
      potential_exposure_information: [
        { id: 'last_date_of_exposure', type: :recent_date, required: true, info_page: true },
        { id: 'continuous_exposure', type: :checkbox, label: 'CONTINUOUS EXPOSURE' },
        { id: 'potential_exposure_location', type: :text, info_page: true },
        { id: 'potential_exposure_country', type: :select, info_page: true },
        { id: 'contact_of_known_case', type: :risk_factor, info_page: true, label: 'Close Contact with a Known Case' },
        { id: 'contact_of_known_case_id', type: :text, info_page: true },
        { id: 'travel_to_affected_country_or_area', type: :risk_factor, info_page: true, label: 'Travel from Affected Country or Area' },
        { id: 'was_in_health_care_facility_with_known_cases', type: :risk_factor, info_page: true, label: 'Was in Healthcare Facility with Known Cases' },
        { id: 'was_in_health_care_facility_with_known_cases_facility_name', type: :text, info_page: true },
        { id: 'laboratory_personnel', type: :risk_factor, info_page: true, label: 'Laboratory Personnel' },
        { id: 'laboratory_personnel_facility_name', type: :text, info_page: true },
        { id: 'healthcare_personnel', type: :risk_factor, info_page: true, label: 'Healthcare Personnel' },
        { id: 'healthcare_personnel_facility_name', type: :text, info_page: true },
        { id: 'crew_on_passenger_or_cargo_flight', type: :risk_factor, info_page: true, label: 'Crew on Passenger or Cargo Flight' },
        { id: 'member_of_a_common_exposure_cohort', type: :risk_factor, info_page: true, label: 'Member of a Common Exposure Cohort' },
        { id: 'member_of_a_common_exposure_cohort_type', type: :text, info_page: true },
        { id: 'symptom_onset', type: :recent_date, required: true, info_page: true },
        { id: 'no_symptom_history', type: :checkbox, label: 'NO SYMPTOM HISTORY' },
        { id: 'first_positive_lab', type: :button, label: 'Enter Lab Result' },
        { id: 'lab_type', type: :select },
        { id: 'specimen_collection', type: :recent_date, required: true, info_page: true },
        { id: 'report', type: :recent_date },
        { id: 'create_first_positive_lab', type: :button, label: 'Create' },
        { id: 'case_status', type: :select, info_page: true },
        { id: 'exposure_notes', type: :text },
        { id: 'jurisdiction_id', type: :text, info_page: true },
        { id: 'update_group_member_jurisdiction_id', type: :checkbox, label: 'Apply this change to the entire household that this monitoree is responsible for' },
        { id: 'assigned_user', type: :text, info_page: true },
        { id: 'update_group_member_assigned_user', type: :checkbox, label: 'Apply this change to the entire household that this monitoree is responsible for' },
        { id: 'exposure_risk_assessment', type: :select },
        { id: 'monitoring_plan', type: :select }
      ]
    }
  end
  # rubocop:enable Layout/LineLength
end
