'USA':
  children:
    'State 1':
      messages:
        assessments:
          html:
            email:
              enrollment:
                info1:
                  eng: |
                    Welcome to symptom monitoring for <a href="http://example.com">State 1 DOH</a>.<br><br>
                    - Lorem<br>
                    - Ipsum
                  spa: |
                    Bienvenido a la monitorización de los síntomas para <a href="http://example.com">El State 1 DOH</a><br><br>
                    - Lorem<br>
                    - Ipsum
          twilio:
            sms:
              prompt:
                intro:
                  # For jurisdictions that use a custom intro SMS message, the privacy policy info will automatically be appended to the custom message
                  # if this link is not already included in the message
                  eng: |
                    You've been identified by State 1 DOH to be enrolled in Sara Alert to be monitored for COVID symptoms.

                    For privacy and more info, visit example.org.
                  spa: |
                    El State 1 DOH lo identifico para inscribirse en Sara Alert para ser monitoreado por sintomas de COVID.

                    Para privacidad y mas informacion, visite example.org.
