const mockTranslations = {
  eng: {
    html: {
      shared: {
        email: 'Email',
        phone: 'Phone',
        webpage: 'Webpage',
      },
      weblink: {
        title: 'Daily Self-Report',
        'bool-title': 'Please select all symptoms which you are experiencing.',
        instruction1: 'If you did not report any symptoms, please continue to follow the recommendations provided by your local health department.',
        instruction2:
          "'If you reported any symptoms, your local health department will be reaching out soon. If you have any immediate concerns, please contact your medical provider or local health department. Avoid close contact with other people and stay at home.'",
        instruction3: 'If you are experiencing a medical emergency, please call 911 and let them know you are being monitored by the health department.',
        instruction4: 'Please use the contact information below to get into contact with a public health official managing your case.',
        submit: 'Submit',
        thank_you: 'Thank You For Completing Your Self Report',
      },
      email: {
        shared: {
          greeting: 'Dear %{name},',
          report: 'Daily Report',
          footer:
            "'Do not reply to this email, forward this email, or share this link. This message was automatically generated by the Sara Alert system and is unique and intended only for you. If you wish to stop receiving these notifications or believe that it was a mistake, please contact your local public health department. For privacy and more info, visit saraalert.org.'",
        },
        enrollment: {
          subject: 'Sara Alert Enrollment',
          header: 'Welcome to the Sara Alert System!',
          info1:
            "'You have been enrolled in the Sara Alert monitoring system. We ask that you provide daily reports of your status. Simply click the button below and follow the on-screen instructions.'",
          info2: 'You will receive a similar reminder daily until your monitoring period has ended.',
        },
        reminder: {
          subject: 'Sara Alert Report Reminder',
          header: 'This is your reminder to complete your daily report.',
          thank_you: 'Thank you for participating in the Sara Alert monitoring program, please fill out your daily report using the link below.',
        },
        closed: {
          subject: 'Sara Alert Reporting Complete',
          header: 'Monitoring complete!',
          thank_you: 'Sara Alert monitoring for %{initials_age} completed on %{completed_date}! Thank you for your participation.',
        },
        contact: {
          info1: 'If you have any questions, please use the contact information below to reach out to the public health organization that helped enroll you:',
          info2: 'If you have any questions please reach out to the public health organization that helped enroll you.',
        },
      },
    },
    twilio: {
      shared: {
        experiencing_symptoms_s: 'Is this person experiencing any of the following symptoms: %{symptom_names}.',
        experiencing_symptoms_p: 'Are any of these people experiencing any of the following symptoms: %{symptom_names}.',
        max_retries_message:
          "'I''m sorry, you have reached the maximum number of response attempts. If you are experiencing a medical emergency, please call 911.'",
      },
      sms: {
        prompt: {
          intro:
            "'Welcome to the Sara Alert system, we will be sending your daily reports for %{name} to this phone number. For privacy and more info, visit saraalert.org.'",
          reminder: 'This is the Sara Alert system reminding you to please reply to our daily-report messages.',
          name: '%{name}',
          daily: 'This is the Sara Alert daily report for: %{names}. %{experiencing_symptoms} Please reply with "Yes" or "No"',
          try_again:
            "'I''m sorry, I didn''t quite get that. Please reply with \"Yes\" or \"No\". If you have any questions, please contact your local health department.'",
          thanks: 'Thank you for completing your daily report!',
        },
        weblink: {
          intro: 'Please complete the Sara Alert Daily Report for %{initials_age}: %{url}',
        },
        closed: {
          thank_you: 'Sara Alert monitoring for %{initials_age} completed on %{completed_date}! Thank you for your participation.',
        },
      },
      voice: {
        intro: 'Hello, this is Sara, the automated public health assistant calling for your daily report.',
        initials_age: '%{initials}, age %{age}',
        daily: 'This is the report for: %{names}. %{experiencing_symptoms}. Please reply with "Yes" or "No"',
        try_again: "I'm sorry, I didn't quite get that. Let's try again.",
        thanks: 'Thank you for completing your daily report! Goodbye.',
      },
    },
    symptoms: {
      chills: {
        name: 'Chills',
      },
      'congestion-or-runny-nose': {
        name: 'Congestion or Runny Nose',
      },
      cough: {
        name: 'Cough',
      },
      diarrhea: {
        name: 'Diarrhea',
      },
      'difficulty-breathing': {
        name: 'Difficulty Breathing',
      },
      fatigue: {
        name: 'Fatigue',
      },
      fever: {
        name: 'Fever',
        notes: 'Feeling feverish or have a measured temperature at or above 100.4°F/38°C',
      },
      headache: {
        name: 'Headache',
      },
      'muscle-pain': {
        name: 'Muscle Pain',
      },
      'nausea-or-vomiting': {
        name: 'Nausea Or Vomiting',
      },
      'new-loss-of-smell': {
        name: 'New Loss of Smell',
      },
      'new-loss-of-taste': {
        name: 'New Loss of Taste',
      },
      'pulse-ox': {
        name: 'Pulse Ox',
        notes: 'What was your lowest oxygen level in the past 24 hours?',
      },
      'repeated-shaking-with-chills': {
        name: 'Repeated Shaking with Chills',
      },
      'shortness-of-breath': {
        name: 'Shortness of Breath',
      },
      'sore-throat': {
        name: 'Sore Throat',
      },
      temperature: {
        name: 'Temperature',
        notes: 'Please enter your current temperature in degrees Fahrenheit',
      },
      'used-a-fever-reducer': {
        name: 'Used A Fever Reducer',
        notes: 'In the past 24 hours, have you used any medicine that reduces fevers?',
      },
      other: {
        name: 'Other',
        notes: 'I would like someone to call me to follow-up on other symptoms or additional needs',
      },
      'no-symptoms': 'I am not experiencing any symptoms',
    },
    'threshold-op': {
      'less-than': 'Less Than',
      'less-than-or-equal': 'Less Than Or Equal to',
      'greater-than': 'Greater Than',
      'greater-than-or-equal': 'Greater Than Or Equal to',
      equal: 'Equal to',
      'not-equal': 'Not Equal to',
    },
  },
  spa: {
    html: {
      shared: {
        email: 'Correo electrónico',
        phone: 'Teléfono',
        webpage: 'Página web',
      },
      weblink: {
        title: 'Reporte diario',
        'bool-title': 'Por favor, seleccione los síntomas que está sintiendo actualmente.',
        instruction1: 'Si Usted no reportó ningún síntoma, por favor siga las recomendaciones proveídas por su departamento de salud local.',
        instruction2:
          "'Si Usted reportó algún síntoma, su departamento de salud local se comunicará pronto con Usted. Si tiene alguna inquietud inmediata, llame a su proveedor médico o al departamento de salud local. Evite el contacto cercano con otras personas y quédese en casa por favor.'",
        instruction3: 'Si tiene una emergencia médica, por favor llame al 911 e infórmeles que el departamento de salud lo está monitoreando.',
        instruction4:
          "'Por favor utilice la información de contacto a continuación para ponerse en contacto con un funcionario de salud pública que esté a cargo de su caso'",
        submit: 'Enviar',
        thank_you: '¡Gracias por completar su informe diario!',
      },
      email: {
        shared: {
          greeting: 'Estimado/a %{name},',
          report: 'Reporte diario',
          footer:
            "'No responda o reenvíe este correo electrónico, ni comparta este enlace. Este mensaje fue generado automáticamente por el sistema Sara Alert y es único y está destinado solo para usted. Si desea dejar de recibir estas notificaciones o piensa que fue un error, por favor pónganse en contacto con su departamento de salud pública local. Para privacidad y más información, visite saraalert.org.'",
        },
        enrollment: {
          subject: 'Inscripción de Sara Alert',
          header: 'Bienvenido al sistema Sara Alert',
          info1:
            "'Usted ha sido inscrito en el sistema de monitoreo Sara Alert. Le pedimos que proporcione informes diarios de su estado de salud. Simplemente haga clic en el botón a continuación y siga las instrucciones en pantalla.'",
          info2: 'Usted recibirá un recordatorio diario similar hasta que finalice su período de monitoreo.',
        },
        reminder: {
          subject: 'Recordatorio del reporte de Sara Alert',
          header: 'Recordatorio del reporte de Sara Alert',
          thank_you: 'Gracias por participar en el programa de monitoreo de Sara Alert. Favor de completar su informe diario utilizando el siguiente enlace.',
        },
        closed: {
          subject: 'Reporte de Sara Alert completo',
          header: 'Reporte de Sara Alert completo',
          thank_you: 'La supervisión de Sara Alert para %{initials_age} se completó el %{completed_date}. Gracias por su participación',
        },
        contact: {
          info1:
            "'Si tiene alguna pregunta, por favor utilice la información de contacto a continuación para comunicarse con la organización de salud pública que le ayudó a inscribirse:'",
          info2: 'Si tiene alguna pregunta, por favor pónganse en contacto con el proveedor de atención médica que le ayudó a inscribirse.',
        },
      },
    },
    twilio: {
      shared: {
        experiencing_symptoms_s: '¿Está usted sintiendo uno o mas de los siguientes síntomas hoy?: %{symptom_names}.',
        experiencing_symptoms_p: '¿Esta alguna de estas personas sintiendo uno o mas de los siguientes síntomas hoy?: %{symptom_names}.',
        max_retries_message: 'Lo siento, ha alcanzado el número máximo de intentos de respuesta. Si tiene una emergencia médica, llame al 911.',
      },
      sms: {
        prompt: {
          intro:
            "'Bienvenido al sistema Sara Alert, le enviaremos sus reportes diarios para %{name} a este número de teléfono. Para privacidad y más información, visite saraalert.org.'",
          reminder: 'Este es el sistema Sara Alert recordándole que por favor responda a nuestros mensajes de reporte diario.',
          daily: 'Este es el informe diario de Sara Alert para: %{names}. %{experiencing_symptoms} Responda con "Sí" o "No"',
          try_again: 'Lo siento, no entendí. Responda con "Sí" o "No"',
          thanks: '¡Gracias por completar su informe diario!',
        },
        weblink: {
          intro: 'Complete el Informe diario de Sara Alert para %{initials_age}: %{url}',
        },
        closed: {
          thank_you: 'La supervisión de Sara Alert para %{initials_age} se completó el %{completed_date}. Gracias por su participación',
        },
      },
      voice: {
        intro: 'Hola, soy Sara, la asistente de salud pública automatizada que solicita su informe diario.',
        initials_age: '%{initials}, años %{age}',
        daily: ' Este es el informe diario de Sara Alert para: %{names}. %{experiencing_symptoms}. Responda con "Sí" o "No"',
        try_again: 'Lo siento, no entendí. Intentemoslo de nuevo.',
        thanks: '¡Gracias por completar su informe diario! Adiós.',
      },
    },
    symptoms: {
      chills: {
        name: 'Escalofrío',
      },
      'congestion-or-runny-nose': {
        name: 'Congestión nasal o un exceso de moco en la nariz',
      },
      cough: {
        name: 'Tos',
      },
      diarrhea: {
        name: 'Diarrea',
      },
      'difficulty-breathing': {
        name: 'Problemas para respirar',
      },
      fatigue: {
        name: 'Fatiga',
      },
      fever: {
        name: 'Fiebre',
        notes: 'Si siente que tiene fiebre o tiene una temperatura igual o superior a 100.4°F/38°C',
      },
      headache: {
        name: 'Dolor de cabeza',
      },
      'muscle-pain': {
        name: 'Dolor muscular',
      },
      'nausea-or-vomiting': {
        name: 'Náuseas o vómitos',
      },
      'new-loss-of-smell': {
        name: 'Pérdida reciente el olfato',
      },
      'new-loss-of-taste': {
        name: 'Pérdida reciente del gusto',
      },
      'pulse-ox': {
        name: 'oxímetro de pulso',
        notes: 'Ingrese la lectura más baja del oxímetro de pulso en las últimas 24 horas',
      },
      'repeated-shaking-with-chills': {
        name: 'Tiembla repetidamente y tiene escalofríos',
      },
      'shortness-of-breath': {
        name: 'Falta de aire',
      },
      'sore-throat': {
        name: 'Dolor de garganta',
      },
      temperature: {
        name: 'Temperatura',
        notes: 'Por favor ingrese su temperatura actual en grados Fahrenheit',
      },
      'used-a-fever-reducer': {
        name: 'Tomó medicina para reducir la fiebre',
        notes: 'En las últimas 24 horas, ¿ha tomado algún medicamento para reducir la fiebre?',
      },
      other: {
        name: 'Otro',
        notes: 'Me gustaría que alguien me llamara para hacer un seguimiento de otros síntomas o necesidades adicionales',
      },
      'no-symptoms': 'No tengo ningún síntoma.',
    },
    'threshold-op': {
      'less-than': 'Menos que',
      'less-than-or-equal': 'Menor o igual a',
      'greater-than': 'Mas grande que',
      'greater-than-or-equal': 'Mayor que o igual a',
      equal: 'Igual a',
      'not-equal': 'no es igual a',
    },
  },
  'spa-pr': {
    html: {
      shared: {
        email: 'Correo electrónico',
        phone: 'Teléfono',
        webpage: 'Página web',
      },
      weblink: {
        title: 'Reporte diario',
        'bool-title': 'Por favor, seleccione los síntomas que está sintiendo actualmente.',
        instruction1: 'Si Usted no reportó ningún síntoma, por favor siga las recomendaciones provistas por su departamento de salud local.',
        instruction2:
          "'Si Usted reportó algún síntoma, su departamento de salud local se comunicará pronto con Usted. Si tiene alguna inquietud inmediata, llame a su proveedor médico o al departamento de salud local. Evite el contacto cercano con otras personas y quédese en casa por favor.'",
        instruction3: 'Si tiene una emergencia médica, por favor llame al 911 e infórmeles que el departamento de salud lo está monitoreando.',
        instruction4:
          "'Por favor utilice la información de contacto a continuación para ponerse en contacto con un funcionario de salud pública que esté a cargo de su caso.'",
        submit: 'Enviar',
        thank_you: '¡Gracias por completar su informe diario!',
      },
      email: {
        shared: {
          greeting: 'Estimado/a %{name},',
          report: 'Reporte diario',
          footer:
            "'No responda o reenvíe este correo electrónico, ni tampoco comparta este enlace. Este mensaje fue generado automáticamente por el sistema Sara Alert y es único y está destinado solo para usted. Si desea dejar de recibir estas notificaciones o piensa que fue un error, por favor pónganse en contacto con su departamento de salud pública local. Para privacidad y más información, visite saraalert.org.'",
        },
        enrollment: {
          subject: 'Inscripción de Sara Alert',
          header: 'Bienvenido al sistema Sara Alert',
          info1:
            "'Usted ha sido inscrito en el sistema de monitoreo Sara Alert. Le pedimos que proporcione informes diarios de su estado de salud. Simplemente haga clic en el botón a continuación y siga las instrucciones en pantalla.'",
          info2: 'Usted recibirá un recordatorio diario similar hasta que finalice su período de monitoreo.',
        },
        reminder: {
          subject: 'Recordatorio del reporte de Sara Alert',
          header: 'Recordatorio del reporte de Sara Alert',
          thank_you: 'Gracias por participar en el programa de monitoreo de Sara Alert. Favor de completar su informe diario utilizando el siguiente enlace.',
        },
        closed: {
          subject: 'Reporte de Sara Alert completo',
          header: 'Reporte de Sara Alert completo',
          thank_you: 'La supervisión de Sara Alert para %{initials_age} se completó el %{completed_date}. Gracias por su participación',
        },
        contact: {
          info1:
            "'Si tiene alguna pregunta, por favor utilice la información de contacto a continuación para comunicarse con la organización de salud pública que le ayudó a inscribirse:'",
          info2: 'Si tiene alguna pregunta, por favor pónganse en contacto con el proveedor de atención médica que le ayudó a inscribirse.',
        },
      },
    },
    twilio: {
      shared: {
        experiencing_symptoms_s: '¿Está usted sintiendo uno o más de los siguientes síntomas hoy?: %{symptom_names}.',
        experiencing_symptoms_p: '¿Esta alguna de estas personas sintiendo uno o más de los siguientes síntomas hoy?: %{symptom_names}.',
        max_retries_message: 'Lo siento, ha alcanzado el número máximo de intentos de respuesta. Si tiene una emergencia médica, llame al 911.',
      },
    },
    sms: {
      prompt: {
        intro:
          "'Bienvenido al sistema Sara Alert, le enviaremos sus reportes diarios para %{name} a este número de teléfono. Para privacidad y más información, visite saraalert.org.'",
        reminder: 'Este es el sistema Sara Alert recordándole que por favor responda a nuestros mensajes de reporte diario.',
        name: '%{name}',
        daily: 'Este es el informe diario de Sara Alert para: %{names}. %{experiencing_symptoms} Responda con "Sí" o "No"',
        try_again: 'Lo siento, no entendí. Responda con "Sí" o "No"',
        thanks: '¡Gracias por completar su informe diario!',
      },
      weblink: {
        intro: 'Complete el Informe diario de Sara Alert para %{initials_age}: %{url}',
      },
      closed: {
        thank_you: 'La supervisión de Sara Alert para %{initials_age} se completó el %{completed_date}. Gracias por su participación',
      },
    },
    voice: {
      intro: 'Hola, soy Sara, la asistente de salud pública automatizada que solicita su informe diario.',
      initials_age: '%{initials}, años %{age}',
      daily: ' Este es el informe diario de Sara Alert para: %{names}. %{experiencing_symptoms}. Responda con "Sí" o "No"',
      try_again: 'Lo siento, no entendí. Intentemoslo de nuevo.',
      thanks: '¡Gracias por completar su informe diario! Adiós.',
    },
    symptoms: {
      chills: {
        name: 'Escalofrío',
      },
      'congestion-or-runny-nose': {
        name: 'Congestión nasal o un exceso de moco en la nariz',
      },
      cough: {
        name: 'Tos',
      },
      diarrhea: {
        name: 'Diarrea',
      },
      'difficulty-breathing': {
        name: 'Problemas para respirar',
      },
      fatigue: {
        name: 'Fatiga',
      },
      fever: {
        name: 'Fiebre',
        notes: 'Se siente que tiene fiebre o tiene una temperatura igual o superior a 100.4°F/38°C',
      },
      headache: {
        name: 'Dolor de cabeza',
      },
      'muscle-pain': {
        name: 'Dolor muscular',
      },
      'nausea-or-vomiting': {
        name: 'Náuseas o vómitos',
      },
      'new-loss-of-smell': {
        name: 'Pérdida reciente el olfato',
      },
      'new-loss-of-taste': {
        name: 'Pérdida reciente del gusto',
      },
      'pulse-ox': {
        name: 'oxímetro de pulso',
        notes: 'Ingrese la lectura más baja del oxímetro de pulso en las últimas 24 horas',
      },
      'repeated-shaking-with-chills': {
        name: 'Tiembla repetidamente y tiene escalofríos',
      },
      'shortness-of-breath': {
        name: 'Falta de aire',
      },
      'sore-throat': {
        name: 'Dolor de garganta',
      },
      temperature: {
        name: 'Temperatura',
        notes: 'Por favor ingrese su temperatura actual en grados Fahrenheit',
      },
      'used-a-fever-reducer': {
        name: 'Tomó medicina para reducir la fiebre',
        notes: 'En las últimas 24 horas, ¿ha tomado algún medicamento para reducir la fiebre?',
      },
      other: {
        name: 'Otro',
        notes: 'Me gustaría que alguien me llamara para hacer un seguimiento de otros síntomas o necesidades adicionales',
      },
      'no-symptoms': 'No tengo ningún síntoma.',
    },
    'threshold-op': {
      'less-than': 'Menos que',
      'less-than-or-equal': 'Menor o igual a',
      'greater-than': 'Mas grande que',
      'greater-than-or-equal': 'Mayor que o igual a',
      equal: 'Igual a',
      'not-equal': 'no es igual a',
    },
  },
  fra: {
    html: {
      shared: {
        email: 'Courriel',
        phone: 'Téléphone',
        webpage: 'Site web',
      },
      weblink: {
        title: 'Rapport quotidien',
        'bool-title': 'Veuillez sélectionner tous les symptômes que vous présentez.',
        instruction1:
          "'Si vous n''avez pas signalé aucun symptôme, veuillez continuer à suivre les recommandations fournies par votre autorité de santé publique locale.'",
        instruction2:
          "'Si vous signalez des symptômes, votre autorité de santé publique locale vous contactera bientôt. Si vous avez des inquiétudes immédiates, veuillez contacter votre fournisseur médical ou votre autorité de santé publique locale. Évitez vos contacts avec les autres et vous devez vous isoler à la maison.'",
        instruction3: "En cas d'urgence médicale, appelez le 911, et faites-leur savoir que vous êtes surveillé par le autorité de santé publique.",
        instruction4: 'Veuillez utiliser les coordonnées ci-dessous si vous souhaitez nous contacter au sujet de votre cas.',
        submit: 'Envoyer',
        thank_you: "Merci d'avoir complété votre rapport quotidien !",
      },
      email: {
        shared: {
          greeting: 'Cher/Chère %{name},',
          report: 'Rapport quotidien',
          footer:
            "'Ne répondez pas à cet e-mail, ne le transférez pas et ne partagez pas ce lien avec quiconque. Ce message a été généré automatiquement par le système d''Alerte Sara ; il est unique et n''est destiné qu''à vous. Si vous souhaitez cesser de recevoir ces notifications ou si vous pensez qu''il s''agit d''une erreur, veuillez contacter les autorités sanitaires locales. Pour la confidentialité et plus d''informations, visitez saraalert.org.'",
        },
        enrollment: {
          subject: 'Recrutement pour alerte Sara',
          header: "Bienvenue sur le système d'Alerte Sara",
          info1:
            "'Vous avez été recruté(e) dans le système de surveillance d''Alerte Sara. Nous vous demandons de fournir des rapports quotidiens sur votre état. Veuillez cliquer sur le bouton ci-dessous et suivre les instructions qui s''affichent à l''écran.'",
          info2: "Vous recevrez un rappel similaire tous les jours jusqu'à ce que votre période de surveillance soit terminée.",
        },
        reminder: {
          subject: "Rappel de rapport d'Alerte Sara",
          header: "Rappel de rapport d'Alerte Sara",
          thank_you:
            "'Merci de participer au programme de surveillance d''Alerte Sara. Veuillez remplir votre rapport quotidien en utilisant le lien ci-dessous.'",
        },
        closed: {
          subject: "Rapport d'Alerte Sara complété",
          header: "Rapport d'Alerte Sara complété",
          thank_you: 'La période de surveillance de Sara Alert pour %{initials_age} a été terminée le %{completed_date} ! Merci de votre participation',
        },
        contact: {
          info1:
            "'Si vous avez des questions, veuillez utiliser les coordonnées ci-dessous pour contacter l''organisation de santé publique qui vous a aidé à vous inscrire:'",
          info2: 'Si vous avez des questions, veuillez contacter le professionnel de santé qui vous a recruté(e).',
        },
      },
    },
    twilio: {
      shared: {
        experiencing_symptoms_s: 'Cette personne est-elle y en a-t-il qui présentent un des symptômes suivants: %{symptom_names}.',
        experiencing_symptoms_p: 'Parmi ces personnes y en a-t-il qui présentent un des symptômes suivants: %{symptom_names}.',
        max_retries_message:
          "'Je suis désolé, vous avez atteint le nombre maximum de tentatives de réponse. Si vous rencontrez une urgence médicale, veuillez appeler le 911.'",
      },
      sms: {
        prompt: {
          intro:
            "'Bienvenue sur le système d''Alerte Sara, nous vous enverrons vos rapports quotidiens pour %{name} à ce numéro de téléphone. Pour la confidentialité et plus d''informations, visitez saraalert.org.'",
          reminder: "Ceci est un rappel du système d'Alerte Sara vous rappelant que vous devez répondre à nos messages de rapport quotidien.",
          name: '%{name}',
          daily: 'Il s\'agit d\'un rapport d\'alerte Sara quotidien destiné aux: %{names}. %{experiencing_symptoms} Veuillez répondre par "Oui" ou par "Non"',
          try_again: 'Je suis désolé, je n\'ai pas compris. Veuillez répondre par "Oui" ou par "Non"',
          thanks: "Merci d'avoir rempli votre rapport quotidien!",
        },
        weblink: {
          intro: 'Veuillez remplir le rapport quotidien de Sara Alert pour %{initials_age}: %{url}',
        },
        closed: {
          thank_you: 'La période de surveillance de Sara Alert pour %{initials_age} a été terminée le %{completed_date} ! Merci de votre participation',
        },
      },
      voice: {
        intro: "Bonjour, voici Sara, l'assistante de santé publique automatisée qui demande votre rapport quotidien.",
        initials_age: '%{initials}, âge %{age}',
        daily: ' Il s\'agit d\'un rapport d\'alerte Sara quotidien destiné aux: %{names}. %{experiencing_symptoms} Veuillez répondre par "Oui" ou par "Non"',
        try_again: "Je suis désolé, je n'ai pas compris. Essayons encore.",
        thanks: "Merci d'avoir rempli votre rapport quotidien! Au revoir.",
      },
    },
    symptoms: {
      chills: {
        name: 'Frissons',
      },
      'congestion-or-runny-nose': {
        name: 'Congestion nasale ou nez qui coule',
      },
      cough: {
        name: 'Toux',
      },
      diarrhea: {
        name: 'Diarrhée',
      },
      'difficulty-breathing': {
        name: 'Difficultés respiratoires',
      },
      fatigue: {
        name: 'Fatigue',
      },
      fever: {
        name: 'Fièvre',
        notes: 'Sensation de fébrilité ou température mesurée supérieure ou égale à 38 °C (100,4 °F)',
      },
      headache: {
        name: 'Maux de tête',
      },
      'muscle-pain': {
        name: 'Douleurs musculaires',
      },
      'nausea-or-vomiting': {
        name: 'Nausées ou vomissements',
      },
      'new-loss-of-smell': {
        name: "Nouvelle perte de l'odorat",
      },
      'new-loss-of-taste': {
        name: 'Nouvelle perte de goût',
      },
      'pulse-ox': {
        name: "d'oxymétrie de pouls",
        notes: "Saisissez votre mesure d'oxymétrie de pouls la plus faible au cours des dernières 24 heures",
      },
      'repeated-shaking-with-chills': {
        name: 'Tremblements répétés accompagnés de frissons',
      },
      'shortness-of-breath': {
        name: 'Essoufflement',
      },
      'sore-throat': {
        name: 'Maux de gorge',
      },
      temperature: {
        name: 'Température',
        notes: 'Veuillez entrer votre température actuelle en degrés Fahrenheit',
      },
      'used-a-fever-reducer': {
        name: "Utilisation d'un agent pour diminuer la fièvre",
        notes: 'Avez-vous utilisé un médicament pour diminuer la fièvre au cours des dernières 24 heures?',
      },
      other: {
        name: 'Other',
        notes: "J'aimerais que quelqu'un m'appelle pour faire le suivi d'autres symptômes ou d'autre chose",
      },
      'no-symptoms': 'Aucun symptôme',
    },
    'threshold-op': {
      'less-than': 'moins que',
      'less-than-or-equal': 'inférieur ou égal à',
      'greater-than': 'plus grand que',
      'greater-than-or-equal': 'Plus grand ou égal à',
      equal: 'égal à',
      'not-equal': 'pas égal à',
    },
  },
  som: {
    html: {
      shared: {
        email: 'Email',
        phone: 'Telefoon',
        webpage: 'Boga shabagada',
      },
      weblink: {
        title: 'Warbixinta Maalinlaha ah',
        'bool-title': 'Fadlan xulo dhammaan astaamaha aad dareemayso.',
        instruction1: 'If you did not report any symptoms, please continue to follow the recommendations provided by your local health department.',
        instruction2:
          "'If you reported any symptoms, your local health department will be reaching out soon. If you have any immediate concerns, please contact your medical provider or local health department. Avoid close contact with other people and stay at home.'",
        instruction3: 'If you are experiencing a medical emergency, please call 911 and let them know you are being monitored by the health department.',
        instruction4: 'Please use the contact information below to get into contact with a public health official managing your case.',
        submit: 'Gudbi',
        thank_you: 'Waad ku mahadsantahay bogida warbixintaada maalinlaha ah!',
      },
      email: {
        shared: {
          greeting: 'Gacaliye/Gacaliso %{name},',
          report: 'Warbixinta Maalinlaha',
          footer:
            "'Ha ka jawaabin iimaylkan, gudbi iimaylkan, ama wadaag xiriiriyaha. Fariintan waxaa si toos ah u soo saaray nidaamka Sara Alert waana mid gaar ah oo adiga kaliya laguugu talagalay. Haddii aad rabto inaad joojiso helitaanka fariimahan ama aad aaminsan tahay in si khaldan laguugu soo diro, fadlan la xiriir waaxda caafimaadka dadweynaha ee deegaanka. Xogta gaarka ah iyo macluumaad dheeri ah, booqo saraalert.org.'",
        },
        enrollment: {
          subject: 'Diiwaangelinta Sara Alert',
          header: 'Ku soo dhowow nidaamka Sara Alert!',
          info1:
            "'Waa lagaa diiwaangeliyay nidaamka la socoshada Sara Alert. Waxaan kaa codsanaynaa inaad bixiso warbixinnada maalinlaha ah ee xaaladaada. Si fudud u guji badhanka hoose oo raac tallaabooyinka shaashada ku yaala.'",
          info2: 'Waxaad heli doontaa xusuusin la mid ah maalin kasta ilaa muddada la socoshadaada ka dhammaato.',
        },
        reminder: {
          subject: 'Xusuusiyaha Sara Alert ee Warbixinta',
          header: 'Kani waa nidaamka Sara Alert oo ku xusuusinayo inaad fadlan jawaab ka bixiso fariimahayaga warbixinta maalinlaha ah.',
          thank_you:
            "'Waad ku mahadsantahay ka qeyb qaadashada barnaamijka la socoshada Sara Alert. Fadlan buuxi warbixintaada maalinlaha ah adoo adeegsanaya xiriiriyaha hoose.'",
        },
        closed: {
          subject: 'Warbixintu Sara Alert way dhammaystiran tahay',
          header: 'Warbixintu Sara Alert way dhammaystiran tahay!',
          thank_you: 'Sara Alert muddada kormeerka for %{initials_age} soo gabagabeeyey %{completed_date}! Waad ku mahadsan tahay ka qayb galka',
        },
        contact: {
          info1:
            "'Haddii aad qabtid wax su''aalo ah, fadlan macluumaad hoos ku qoran u isticmaal si aad u gaadho hay''ad caafimaadka dadweynaha in caawisay kuu soo diiwaangelin:'",
          info2: "Haddii aad qabtid wax su'aalo ah, fadlan la xiriir xirfadlaha daryeelka caafimaadka kaasoo kaa caawiyay in lagu diiwaangeliyo.",
        },
      },
    },
    twilio: {
      shared: {
        experiencing_symptoms_s: 'Qofkani ma wax ka mid ah astaamaha soo socda: %{symptom_names}.',
        experiencing_symptoms_p: 'Miyuu mid ka mid ah dadkani wax ka mid ah astaamaha soo socda: %{symptom_names}.',
        max_retries_message:
          "'Waan ka xumahay, waxaad gaadhay tirada ugu badan ee isku day jawaab celin ah. Haddii aad la kulanto xaalad caafimaad oo degdeg ah, fadlan wac 911.'",
      },
      sms: {
        prompt: {
          intro:
            "'Ku soo dhowow nidaamka Sara Alert, waxaan ku soo diri doonnaa warbixinadaada maalinlaha ah ee loogu talagalay %{name} lambarkan telefoon. Xogta gaarka ah iyo macluumaad dheeri ah, booqo saraalert.org.'",
          reminder: 'Kani waa nidaamka Sara Alert oo ku xusuusinayo inaad fadlan jawaab ka bixiso fariimahayaga warbixinta maalinlaha ah.',
          name: '%{name}',
          daily: 'Tani waa warbixinta maalinlaha ah ee Sara Alert ee loogu talagalay: %{names}. %{experiencing_symptoms} Ku jawaab "Haa" ama "Maya"',
          try_again: 'Waan ka xumahay, maan fahmin. Ku jawaab "Haa" ama "Maya"',
          thanks: 'Waad ku mahadsan tahay dhammaystirka warbixin maalmeedkaaga!',
        },
        weblink: {
          intro: 'Fadlan u buuxi Warbixinta Maalinlaha ee Sara Alert ee %{initials_age}: %{url}',
        },
        closed: {
          thank_you: 'Sara Alert muddada kormeerka for %{initials_age} soo gabagabeeyey %{completed_date}! Waad ku mahadsan tahay ka qayb galka',
        },
      },
      voice: {
        intro: 'Waa salaaman tahay Sara Alert oo ugu yeeraysa warbixintaada maalinlaha ah.',
        initials_age: '%{initials}, %{age}',
        daily: ' Tani waa warbixinta maalinlaha ah ee Sara Alert ee loogu talagalay: %{names}. %{experiencing_symptoms}. Ku jawaab "Haa" ama "Maya"',
        try_again: 'Waan ka xumahay, maan fahmin. Aan isku dayno markale.',
        thanks: 'Waad ku mahadsan tahay dhammaystirka warbixin maalmeedkaaga! Nabad galyo',
      },
    },
    symptoms: {
      chills: {
        name: 'Qarqaryo',
      },
      'congestion-or-runny-nose': {
        name: 'San xidhan ama duuf leh',
      },
      cough: {
        name: 'Qufac',
      },
      diarrhea: {
        name: 'Shuban',
      },
      'difficulty-breathing': {
        name: 'Neef-qabasho',
      },
      fatigue: {
        name: 'Daal',
      },
      fever: {
        name: 'Qandho',
        notes: 'Dareemida xummad ama xaraarad cabbirkeedu yahay ama ka sareysa 100.4°F/38°C',
      },
      headache: {
        name: 'Madax-xanuun',
      },
      'muscle-pain': {
        name: 'Murqo-xanuun',
      },
      'nausea-or-vomiting': {
        name: 'Lalabbo ama matagid',
      },
      'new-loss-of-smell': {
        name: 'ur cusub kaa lunta',
      },
      'new-loss-of-taste': {
        name: 'Dhadhan kaa lunta',
      },
      'pulse-ox': {
        name: 'Aksijiinta Dhiiggaaga',
        notes: 'Geli cabbirka aksijiinta dhiiggaaga ee ugu hooseeya ee la qaaday 24-kii saac ee la soo dhaafay',
      },
      'repeated-shaking-with-chills': {
        name: 'Gariir wata Qarqaryo oo soo noqnoqda',
      },
      'shortness-of-breath': {
        name: 'Neef qabatin',
      },
      'sore-throat': {
        name: 'Cune-xanuun',
      },
      temperature: {
        name: 'Temperature',
        notes: 'Please enter your current temperature in degrees Fahrenheit',
      },
      'used-a-fever-reducer': {
        name: "Isticmaalay Xanuun-baa'bi'iye",
        notes: "24-kii saac ee la soo dhaafay, ma isticmaashay wax daawo ah oo qanshada baa'bi'isa?",
      },
      other: {
        name: 'Other',
        notes: 'I would like someone to call me to follow-up on other symptoms or additional needs',
      },
      'no-symptoms': 'Astaamo ma laha',
    },
    'threshold-op': {
      'less-than': 'Ka yar',
      'less-than-or-equal': 'Kayar ama Sinnaansho',
      'greater-than': 'Ka Weyn',
      'greater-than-or-equal': 'Ka Weyn ama Ka siman tahay',
      equal: 'Loo siman yahay',
      'not-equal': 'Lama sinna',
    },
  },
  kor: {
    html: {
      shared: {
        email: '전자 메일',
        phone: '전화',
        webpage: '웹 페이지',
      },
      weblink: {
        title: '일일 자기 보고서',
        'bool-title': '겪고 계신 모든 증상을 선택해 주십시오.',
        instruction1: '아무 증상도 보고하지 않으셨다면, 계속해서 지역 보건부가 제공하는 권고사항을 따라 주십시오.',
        instruction2:
          '어떠한 증상을 보고하셨다면, 곧 지역 보건부로부터 연락을 받으시게 됩니다. 즉각적인 대처가 필요한 경우는 의료 제공자나 지역 보건부에 문의하시기 바랍니다. 다른 사람들과의 접촉을 피하고 집에 머물러 주십시오.',
        instruction3: '응급 의료 상황을 겪고 계신다면 911에 전화하셔서 보건부에 의해 모니터링되고 있음을 알려주시기 바랍니다.',
        instruction4: '아래의 연락처 정보를 이용하여 귀하의 케이스를 담당하고 있는 공중 보건인과 연락을 취하실 수 있습니다.',
        submit: '제출',
        thank_you: '자기 보고서를 작성해 주셔서 감사합니다.',
      },
      email: {
        shared: {
          greeting: '%{name}님,',
          report: '일일 보고서',
          footer:
            '이 이메일에 답장하거나, 이 이메일을 전달하거나, 이 링크를 공유하지 마십시오. 이 메시지는 Sara Alert 시스템에 의해 자동으로 생성되었으며 고유하고 귀하만을 위한 것입니다. 이러한 알림을 중단하고 싶거나 실수라고 생각되면 지역 공중 보건부에 문의하십시오. 개인 정보 보호 및 더 자세한 정보를 원하시면 saraalert.org를 방문하십시오.',
        },
        enrollment: {
          subject: 'Sara Alert 등록',
          header: 'Sara Alert 시스템에 오신 것을 환영합니다!',
          info1:
            'Sara Alert 모니터링 시스템에 등록되셨습니다. 귀하의 상태에 대한 일일 보고서를 제공해 주시기를 부탁드립니다. 아래의 버튼을 클릭한 후, 화면의 지시를 따라주시면 됩니다.',
          info2: '모니터링 기간이 끝날 때까지 매일 비슷한 알림을 받으시게 됩니다.',
        },
        reminder: {
          subject: 'Sara Alert 보고서 알림',
          header: '일일 보고서 작성 알림입니다.',
          thank_you: 'Sara Alert 모니터링 시스템에 참여해 주셔서 감사합니다. 아래의 링크를 사용하여 일일 보고서를 작성해 주시기 바랍니다.',
        },
        closed: {
          subject: 'Sara Alert 모니터링 종료',
          header: '모니터링이 종료되었습니다.',
          thank_you: '%{initials_age}에 대한 Sara Alert 모니터링이 %{completed_date}일에 완료되었습니다.참여해 주셔서 감사합니다.',
        },
        contact: {
          info1: '질문이 있으시면 등록을 도와드린 공중 보건 기관에 문의하시기 바랍니다:',
          info2: '질문이 있으시면 등록을 도와드린 공중 보건 기관에 문의하시기 바랍니다.',
        },
      },
    },
    twilio: {
      shared: {
        experiencing_symptoms_s: '다음과 같은 증상을 겪고 계십니까? %{symptom_names}.',
        experiencing_symptoms_p: '이 분들 중에 다음과 같은 증상을 겪고 계신 분이 있으십니까? %{symptom_names}.',
        max_retries_message:
          '미안 해요, 최대 응답 시도 횟수에 도달했습니다. 당신이 응급 상황이 발생하는 경우, 911에 전화해서 당신이 보건 당국에 의해 감시되고있다 알려 주시기 바랍니다.',
      },
      sms: {
        prompt: {
          intro:
            'Sara Alert 시스템에 오신 것을 환영합니다. 이 전화번호로 %{name}님의 일일 보고서를 보내드리겠습니다. 개인 정보 보호 및 더 자세한 정보를 원하시면 saraalert.org를 방문하십시오.',
          reminder: '이것은 Sara Alert로서 우리에게 일일 보고서 메시지에 회신해 주길 바랍니다.',
          name: '%{name}님',
          daily: '이것은 %{names}의 Sara Alert 일일 보고서입니다. %{experiencing_symptoms} "네" 또는 "아니요"로 대답해 주시기 바랍니다.',
          try_again: '죄송합니다만 이해하지 못했습니다. "네" 또는 "아니요"로 대답해 주시기 바랍니다. 질문이 있으시면 지역 보건부에 문의하십시오.',
          thanks: '일일 보고서를 작성해 주셔서 감사합니다.',
        },
        weblink: {
          intro: '이것은 님의 Sara Alert 일일 보고서입니다 %{initials_age}: %{url}',
        },
        closed: {
          thank_you: '%{initials_age}에 대한 Sara Alert 모니터링이 %{completed_date}일에 완료되었습니다.참여해 주셔서 감사합니다.',
        },
      },
      voice: {
        intro: '안녕하십니까? 자동화된 공중 보건 보조원 Sara가 일일 보고서를 요청합니다.',
        initials_age: '%{age} 세 %{initials} 님',
        daily: '이것은 %{names} 보고서입니다. %{experiencing_symptoms} "네" 또는 "아니요"로 대답해 주시기 바랍니다.',
        try_again: '죄송합니다만 이해하지 못했습니다. 다시 해봅시다.',
        thanks: '일일 보고서를 작성해 주셔서 감사합니다. 안녕히 가십시오.',
      },
    },
    symptoms: {
      chills: {
        name: '오한',
      },
      'congestion-or-runny-nose': {
        name: '코막힘 또는 콧물',
      },
      cough: {
        name: '기침',
      },
      diarrhea: {
        name: '설사',
      },
      'difficulty-breathing': {
        name: '호흡곤란',
      },
      fatigue: {
        name: '피로',
      },
      fever: {
        name: '발열',
        notes: '미열이 감지되거나 100.4°F/38°C 이상의 고열이 측정됨',
      },
      headache: {
        name: '두통',
      },
      'muscle-pain': {
        name: '근육통',
      },
      'nausea-or-vomiting': {
        name: '메스꺼움 또는 구토',
      },
      'new-loss-of-smell': {
        name: '새로운 후각소실',
      },
      'new-loss-of-taste': {
        name: '새로운 미각소실',
      },
      'pulse-ox': {
        name: '혈중 산소 소준',
        notes: '지난 24시간 동안 가장 낮은 산소 수치는 얼마였나요?',
      },
      'repeated-shaking-with-chills': {
        name: '오한을 동반한 지속적 떨림',
      },
      'shortness-of-breath': {
        name: '숨참',
      },
      'sore-throat': {
        name: '인후통',
      },
      temperature: {
        name: '온도',
        notes: '체온를 입력하십시오(화씨).',
      },
      'used-a-fever-reducer': {
        name: '해열제를 사용했음',
        notes: '지난 24시간 동안 열을 줄이기 위해 약을 먹었나요?',
      },
      other: {
        name: '기타',
        notes: '다른 증상이나 추가 필요사항에 대해 후속 조치를 받을 수 있는 사람이 있으면 좋겠습니다',
      },
      'no-symptoms': '증상이 없습니다',
    },
    'threshold-op': {
      'less-than': '미만',
      'less-than-or-equal': '작거나 같음',
      'greater-than': '보다 큼',
      'greater-than-or-equal': '크거나 같음',
      equal: '같음',
      'not-equal': '같지 않음',
    },
  },
  vie: {
    html: {
      shared: {
        email: 'Email',
        phone: 'Điện thoại',
        webpage: 'Trang web',
      },
      weblink: {
        title: 'Tự Báo cáo Hàng ngày',
        'bool-title': 'Xin vui lòng chọn tất cả các triệu chứng mà bạn đang gặp phải.',
        instruction1: 'Nếu bạn không báo cáo bất kỳ triệu chứng nào, vui lòng tiếp tục làm theo các khuyến nghị do sở y tế địa phương cung cấp.',
        instruction2:
          'Nếu bạn báo cáo bất kỳ triệu chứng nào, bộ phận y tế địa phương của bạn sẽ sớm liên hệ với bạn. Nếu bạn có bất kỳ thắc mắc nào, ngay lập tức, xin vui lòng liên hệ với nhà cung cấp dịch vụ y tế hoặc sở y tế địa phương. Tránh tiếp xúc gần gũi với người khác và xin vui lòng ở nhà.',
        instruction3: 'Nếu bạn đang gặp trường hợp khẩn cấp về y tế, xin vui lòng gọi 911 và cho họ biết bạn đang được bộ phận y tế theo dõi.',
        instruction4: 'Xin vui lòng sử dụng thông tin liên hệ bên dưới để liên hệ với một quan chức y tế công cộng quản lý trường hợp của bạn.',
        submit: 'Gửi đi',
        thank_you: 'Cảm ơn bạn đã hoàn thành bản báo cáo của mình.',
      },
      email: {
        shared: {
          greeting: 'Kính gửi %{name},',
          report: 'Báo cáo hàng ngày',
          footer:
            'Xin đừng trả lời email này, chuyển tiếp email này hoặc chia sẻ liên kết này. Thông báo này được tạo tự động bởi hệ thống Sara Alert và là duy nhất và chỉ dành cho bạn. Nếu bạn muốn ngừng nhận những thông báo này hoặc tin rằng đó là do nhầm lẫn, vui lòng liên hệ với sở y tế công cộng địa phương của bạn. Để biết về quyền riêng tư và biết thêm thông tin, hãy truy cập saraalert.org.',
        },
        enrollment: {
          subject: 'Đăng ký Sara Alert',
          header: 'Chào mừng bạn đến với Hệ thống Cảnh báo Sara',
          greeting: 'Kính gửi %{name},',
          info1:
            'Bạn đã được đăng ký vào hệ thống giám sát Sara Alert. Chúng tôi yêu cầu bạn cung cấp các báo cáo hàng ngày về tình trạng của bạn. Chỉ cần nhấn vào nút bên dưới và làm theo hướng dẫn trên màn hình.',
          info2: 'Bạn sẽ nhận được một lời nhắc tương tự hàng ngày cho đến khi thời gian theo dõi của bạn kết thúc.',
        },
        reminder: {
          subject: 'Lời nhắc Báo cáo Cảnh báo Sara',
          header: 'Đây là lời nhắc của bạn để hoàn thành báo cáo hàng ngày của bạn.',
          thank_you:
            'Cảm ơn bạn đã tham gia vào chương trình theo dõi Sara Alert, xin vui lòng điền vào báo cáo hàng ngày của bạn bằng cách sử dụng liên kết bên dưới.',
        },
        closed: {
          subject: 'Hoàn thành theo dõi cảnh báo Sara',
          header: 'Quá trình giám sát hoàn tất!',
          thank_you: 'Sara Alert giám sát cho %{initials_age} hoàn thành vào %{completed_date}! Cảm ơn bạn vì sự tham gia của bạn.',
        },
        contact: {
          info1: 'Nếu bạn có bất kỳ câu hỏi nào, vui lòng liên hệ với tổ chức y tế công cộng, nơi đã giúp đăng ký cho bạn:',
          info2: 'Nếu bạn có bất kỳ câu hỏi nào, vui lòng liên hệ với tổ chức y tế công cộng, nơi đã giúp đăng ký cho bạn.',
        },
      },
    },
    twilio: {
      shared: {
        experiencing_symptoms_s: 'Người này có gặp bất kỳ triệu chứng nào sau đây không? %{symptom_names}.',
        experiencing_symptoms_p: 'Có ai trong số những người này gặp bất kỳ triệu chứng nào sau đây không? %{symptom_names}.',
        max_retries_message:
          'Tôi xin lỗi, bạn đã đạt đến số lần thử phản hồi tối đa. Nếu bạn đang gặp một trường hợp khẩn cấp y tế, xin vui lòng gọi số 911 và cho họ biết bạn đang được theo dõi bởi các bộ phận y tế.',
      },
      sms: {
        prompt: {
          intro:
            'Chào mừng bạn đến với hệ thống Sara Alert, chúng tôi sẽ gửi các báo cáo hàng ngày của bạn cho %{name} tới số điện thoại này. Để biết về quyền riêng tư và biết thêm thông tin, hãy truy cập saraalert.org.',
          reminder: 'Đây là Sara Alert nhắc nhở bạn để vui lòng trả lời để hoàn thành báo cáo hàng ngày của bạn.',
          name: '%{name}',
          daily: 'Đây là bản báo cáo hàng ngày của Sara Alert cho: %{names}. %{experiencing_symptoms} Xin vui lòng trả lời "Có" hoặc "Không"',
          try_again:
            'Tôi xin lỗi, tôi không hiểu lắm. Xin vui lòng trả lời bằng \\ "Có \\" hoặc \\ "Không \\". Nếu bạn có bất kỳ câu hỏi nào, xin vui lòng liên hệ với sở y tế địa phương của bạn.',
          thanks: 'Cảm ơn bạn đã hoàn thành báo cáo hàng ngày của mình',
        },
        weblink: {
          intro: 'Đây là bản báo cáo hàng ngày của Sara Alert cho %{initials_age}: %{url}',
        },
        closed: {
          thank_you: 'Sara Alert giám sát cho %{initials_age} hoàn thành vào %{completed_date}! Cảm ơn bạn vì sự tham gia của bạn.',
        },
      },
      voice: {
        intro: 'Xin chào, đây là Sara, trợ lý y tế công cộng tự động đang gọi cho báo cáo hàng ngày của bạn.',
        initials_age: '%{initials}, %{age} tuổi',
        daily: 'Đây là bản báo cáo hàng ngày của Sara Alert cho: %{names}. %{experiencing_symptoms}. Xin vui lòng trả lời "Có" hoặc "Không"',
        try_again: 'Tôi xin lỗi, tôi không hiểu lắm. Hãy thử lại lần nữa.',
        thanks: 'Cảm ơn bạn đã hoàn thành báo cáo hàng ngày của mình! Tạm biệt.',
      },
    },
    symptoms: {
      chills: {
        name: 'Ớn lạnh',
      },
      'congestion-or-runny-nose': {
        name: 'Nghẹt mũi hoặc chảy nước mũi',
      },
      cough: {
        name: 'Ho',
      },
      diarrhea: {
        name: 'Tiêu chảy',
      },
      'difficulty-breathing': {
        name: 'Khó thở',
      },
      fatigue: {
        name: 'Mệt mỏi',
      },
      fever: {
        name: 'Sốt',
        notes: 'Cảm thấy sốt hoặc nhiệt độ đo được bằng hoặc trên 100,4°F/38°C',
      },
      headache: {
        name: 'Đau đầu',
      },
      'muscle-pain': {
        name: 'Đau cơ',
      },
      'nausea-or-vomiting': {
        name: 'Buồn nôn hoặc nôn mửa',
      },
      'new-loss-of-smell': {
        name: 'Mất mùi mới',
      },
      'new-loss-of-taste': {
        name: 'Mất vị giác mới',
      },
      'pulse-ox': {
        name: 'Lượng oxy trong máu',
        notes: 'Mức độ bão hoà ô-xy thấp nhất của bạn trong 24 giờ qua là bao nhiêu?',
      },
      'repeated-shaking-with-chills': {
        name: 'Run rẩy lặp đi lặp lại kèm theo ớn lạnh',
      },
      'shortness-of-breath': {
        name: 'Hơi thở ngắn',
      },
      'sore-throat': {
        name: 'Đau họng',
      },
      temperature: {
        name: 'Nhiệt độ',
        notes: 'Vui lòng nhập nhiệt độ hiện tại của bạn theo độ F',
      },
      'used-a-fever-reducer': {
        name: 'Sử dụng thuốc hạ sốt',
        notes: 'Trong 24 giờ qua, bạn đã sử dụng bất kỳ loại thuốc nào làm giảm sốt chưa?',
      },
      other: {
        name: 'Khác',
        notes: 'Tôi muốn ai đó gọi cho tôi để theo dõi các triệu chứng khác hoặc nhu cầu bổ sung',
      },
      'no-symptoms': 'Tôi không có triệu chứng nào cả',
    },
    'threshold-op': {
      'less-than': 'nhỏ hơn',
      'less-than-or-equal': 'nhỏ hơn hoặc bằng',
      'greater-than': 'lớn hơn',
      'greater-than-or-equal': 'lớn hơn hoặc bằng',
      equal: 'bằng',
      'not-equal': 'không bằng',
    },
  },
  rus: {
    html: {
      shared: {
        email: 'Электронная почта',
        phone: 'Телефон',
        webpage: 'Сайт',
      },
      weblink: {
        title: 'Заполнение ежедневного опросника',
        'bool-title': 'Пожалуйста, выберите все симптомы, которые у вас есть на данный момент',
        instruction1: 'Если Вы сообщили о каких-либо симптомах, с Вами в скором времени всяжутся сотрудники местного отдела общественного здравоохранения.',
        instruction2:
          'Если у Вас возникли неотложные причины для беспокойства, пожалуйста незамедлительно свяжитесь со своим лечащим врачом или местным отделом общественного здравоохранения. Пожалуйста, избегайте близкого контакта с людьми и оставайтесь дома.',
        instruction3:
          'Если Вам требуется срочная медицинская помощь, пожалуйста, наберите 911 и скажите им, что что Вы находитесь под контролем департамента здравоохранения',
        instruction4:
          'Пожалуйста, используйте указанную ниже контактную информацию для общения с сотрудниками местного отдела общественного здравоохранения, занимающимися вашим случаем.',
        submit: 'отправить',
        thank_you: 'Благодарим за заполнение опросника.',
        email: 'Электронная почта',
        phone: 'Телефон',
        webpage: 'Сайт',
      },
      email: {
        shared: {
          greeting: 'Здравствуйте %{name},',
          report: 'ежедневный опрос',
          footer:
            'Отвечать, пересылать и делится ссылкой на это сообщение не нужно. Это сообщение автоматически создано системой Sara Alert и предназначено только для Вас. Если Вы не хотите получать сообщения или считаете, что произошла ошибка, обратитесь в местный отдел общественного здравоохранения.  Чтобы подробнее узнать о программе, системе конфиденциальности, а также получить дополнительную информацию, посетите saraalert.org.',
        },
        enrollment: {
          subject: 'Вы были зарегистрированы в Sara Alert',
          header: 'Добро пожаловать в систему Sara Alert!',
          greeting: 'Здравствуйте %{name},',
          info1:
            'Вы были зарегистрированы в системе мониторинга Sara Alert. Мы будем Вам очень признательны, если Вы ежедневно будете присылать нам отчеты о состоянии вашего здоровья в день получения Вами этого сообщения. Пожалуйста, нажмите на ссылку внизу и следуйте инструкциям на экране.',
          info2: 'Вы будете получать  подобное напоминание ежедневно вплоть до окончания периода мониторинга.',
        },
        reminder: {
          subject: 'Напоминание об опросе о самочувствии, Sara Alert',
          header: 'Хотим напомнить, что сегодня Вы не завершили заполнение ежедневного опросника о состоянии вашего здоровья.',
          thank_you:
            'Спасибо за Ваше участвуете в программе мониторинга Sara Alert. Пожалуйста, заполните ежедневный опросник о состоянии вашего здоровья за сегодняшний день, перейдя по ссылке внизу.',
        },
        closed: {
          subject: 'Ваш период мониторинга Sara Alert завершен',
          header: 'Ваш мониторинг завершен!',
          thank_you: 'Мониторинг Sara Alert для %{initials_age} завершено %{completed_date}! Спасибо за ваше участие.',
        },
        contact: {
          info1:
            'Если у вас есть какие-либо вопросы, пожалуйста, обратиться к организации общественного здравоохранения, которые помогли зарегистрировать вас:',
          info2: 'Если у Вас возникнут вопросы, пожалуйста, обратитесь в  организацию общественного здравоохранения, в которой помогли Вас зарегистрировать.',
        },
      },
    },
    twilio: {
      shared: {
        experiencing_symptoms_s: 'Есть ли сегодня у %{name} какие-либо из следующих симптомов: %{symptom_names}.',
        experiencing_symptoms_p: 'Испытывает ли кто-то какие-либо из следующих симптомов: %{symptom_names}.',
        max_retries_message:
          'Простите, достигнуто максимальное число попыток ответа. Если вы столкнулись с неотложной медицинской помощи, пожалуйста, позвоните по телефону 911.',
      },
      sms: {
        prompt: {
          intro:
            'Добро пожаловать в систему Sara Alert. Мы будем отправлятьежедневные опросы для %{name} на этот номер телефона.  Чтобы подробнее узнать о программе, системе конфиденциальности, а также получить дополнительную информацию, посетите saraalert.org.',
          reminder: 'This is the Sara Alert system reminding you to please reply to our daily-report messages.',
          name: '%{name}',
          daily:
            'Это Sara Alert, ежедневный опрос о самочувствии %{names}. %{experiencing_symptoms} Пожалуйста, ответьте «Да» или «Нет» на каждый из предложенных вопросов.',
          try_again:
            'Простите, пожалуйста, я не совсем понял ответ. Пожалуйста, ответьте «Да» или «Нет». Если у вас есть какие-либо вопросы, обратитесь в местный отдел общественного здравоохранения.',
          thanks: 'Спасибо, что заполнили наш ежедневный опросник.',
        },
        weblink: {
          intro: 'Это Sara Alert, ежедневный опрос о самочувствии %{initials_age}: %{url}',
        },
        closed: {
          thank_you: 'Мониторинг Sara Alert для %{initials_age} завершено %{completed_date}! Спасибо за ваше участие.',
        },
      },
      voice: {
        intro: 'Здравствуйте, это "Sara", Ваш роботизированный помощник из отдела здравоохранения.',
        initials_age: '%{initials}, возраста %{age}',
        daily:
          'Это Sara Alert, ежедневный опрос о самочувствии: %{names}. %{experiencing_symptoms}. Пожалуйста, ответьте «Да» или «Нет» на каждый из предложенных вопросов.',
        try_again: 'Простите, пожалуйста, я не совсем понял ответ. Давайте попробуем снова.',
        thanks: 'Спасибо, что заполнили наш ежедневный опросник! До свидания.',
      },
    },
    symptoms: {
      chills: {
        name: 'озноб',
      },
      'congestion-or-runny-nose': {
        name: 'Заложенность носа и сопли',
      },
      cough: {
        name: 'Кашель',
      },
      diarrhea: {
        name: 'диарея',
      },
      'difficulty-breathing': {
        name: 'Затруднённое дыхание',
      },
      fatigue: {
        name: 'Усталость',
      },
      fever: {
        name: 'Температура',
        notes: 'Ощущение, что у вас высокая температура или (при измерении) температура около или выше 38 градусов.',
      },
      headache: {
        name: 'Головная боль',
      },
      'muscle-pain': {
        name: 'Мышечная боль',
      },
      'nausea-or-vomiting': {
        name: 'Тошнота или рвота',
      },
      'new-loss-of-smell': {
        name: 'Новоприобретённая потеря обоняния',
      },
      'new-loss-of-taste': {
        name: 'Новоприобретённая потеря вкуса ',
      },
      'pulse-ox': {
        name: 'пульсоксиметрия',
        notes: 'Каков был ваш самый низкий уровень кислорода за последние 24 часа?',
      },
      'repeated-shaking-with-chills': {
        name: 'озноб',
      },
      'shortness-of-breath': {
        name: 'одышка',
      },
      'sore-throat': {
        name: 'Боль в горле',
      },
      temperature: {
        name: 'температура',
        notes: 'Введите температуру в градусах по Фаренгейту',
      },
      'used-a-fever-reducer': {
        name: 'Прием жаропонижающих препаратов',
        notes: 'За последние 24 часа вы использовали какие-нибудь лекарства, которые уменьшают лихорадку?',
      },
      other: {
        name: 'прочее',
        notes: 'Я хотел бы, чтобы кто-то позвонил мне, чтобы проследить за другими симптомами или дополнительными потребностями',
      },
      'no-symptoms': 'У меня нет никаких симптомов',
    },
    'threshold-op': {
      'less-than': 'меньше',
      'less-than-or-equal': 'меньше или равно',
      'greater-than': 'больше, чем',
      'greater-than-or-equal': 'больше или равно',
      equal: 'равна',
      'not-equal': 'не равную',
    },
  },
  ara: {
    html: {
      shared: {
        email: 'البريد الإلكتروني',
        phone: 'الهاتف',
        webpage: 'صفحة الويب',
      },
      weblink: {
        title: 'التقرير الذاتي اليومي',
        'bool-title': 'الرجاء تحديد جميع الأعراض التي تعاني منها',
        instruction1: 'إذا لم تبلغ عن أي أعراض ، فيرجى الاستمرار في اتباع التوصيات المقدمة من وزارة الصحة المحلية.',
        instruction2:
          'إذا أبلغت عن أي أعراض ، فستتواصل إدارة الصحة المحلية قريبًا. إذا كان لديك أي مخاوف فورية ، يرجى الاتصال بمزود الخدمة الطبية أو الصحة المحلية',
        instruction3: 'إذا كنت تعاني من حالة طبية طارئة، فيرجى الاتصال برقم 911 وإبلاغهم بأنك تحت المتابعة الصحية.',
        instruction4: 'يرجى استخدام معلومات الاتصال أدناه للتواصل مع مسؤول الصحة العامة الذي يتابع حالتك.',
        submit: 'إرسال',
        thank_you: 'أشكركم',
      },
      email: {
        shared: {
          greeting: 'عزيزي %{name} ،',
          report: 'تقريرك اليومي',
          footer:
            'تم إنشاؤه بواسطة نظام Sara Alert وهو فريد ومخصص لك فقط. إذا كنت ترغب في التوقف عن تلقي هذه الإخطارات أو تعتقد أنه كان خطأ، يرجى الاتصال بقسم الصحة العامة المحلي. للخصوصية ومزيد من المعلومات، قم بزيارة saraalert.org.',
        },
        enrollment: {
          subject: 'تسجيل Sara Alert',
          header: 'مرحبًا بك في نظام تنبيه سارة',
          info1:
            'لقد تم تسجيلك في نظام مراقبة Sara Alert. نطلب منك تقديم تقارير يومية عن حالتك. ما عليك سوى النقر فوق الزر أدناه واتباع التعليمات التي تظهر على الشاشة.',
          info2: 'سوف تتلقى تذكيرًا مشابهًا يوميًا حتى انتهاء فترة المتابعة الخاصة بك.',
        },
        reminder: {
          subject: 'تذكير تقرير تنبيه سارة',
          header: 'هذا هو تذكيرك لإكمال تقريرك اليومي.',
          thank_you: 'شكرًا لك على المشاركة في برنامج Sara Alert للمراقبة، يرجى ملء تقريرك اليومي باستخدام الرابط أدناه.',
        },
        closed: {
          subject: 'اكتمال متابعة تنبيه سارة',
          header: 'اكتملت المتابعة!',
          thank_you: 'Sara Alert اكتملت مرمتابعة %{initials_age} في %{completed_date}! أشكركم على مشاركتكم.',
        },
        contact: {
          info1: 'إذا كانت لديك أي أسئلة، فيرجى التواصل مع قسم الصحة العامة التي ساعدت في تسجيلك:',
          info2: 'إذا كانت لديك أي أسئلة، فيرجى التواصل مع قسم الصحة العامة التي ساعدت في تسجيلك.',
        },
      },
    },
    twilio: {
      shared: {
        experiencing_symptoms_s: 'هل يعاني هذا الشخص من أي من الأعراض التالية: %{symptom_names}',
        experiencing_symptoms_p: 'هل يعاني أي من هؤلاء الأشخاص من أي من الأعراض التالية: %{symptom_names}.',
        max_retries_message:
          'أنا آسف لقد وصلت إلى الحد الأقصى لعدد محاولات الاستجابة. ذا كنت تعاني من حالة طبية طارئة، يرجى الاتصال بالرقم 911 واجعلهم يعرفون ما يجري رصده لك من قبل وزارة الصحة.',
      },
      sms: {
        prompt: {
          intro: 'مرحبًا بك في نظام Sara Alert، سنرسل لك تقاريرك اليومية عن %{name} إلى رقم هذا الهاتف. للخصوصية ومزيد من المعلومات، قم بزيارة saraalert.org.',
          reminder: 'هذا تذكير Sara Alert للرد على رسائل التقرير اليومي.',
          name: '%{name}',
          daily: 'هذا هو تقرير Sara Alert اليومي لـ: %{names}. %{experiencing_symptoms} الرجاء الرد بـ "نعم" أو "لا"',
          try_again: 'أنا آسف لم أفهم. الرجاء الرد بـ "نعم" أو "لا". إذا كانت لديك أي أسئلة ، يرجى الاتصال بقسم الصحة المحلي.',
          thanks: 'شكرا لاستكمال تقريرك اليومي',
        },
        weblink: {
          intro: 'هذا هو تقرير Sara Alert اليومي لـ %{initials_age}: %{url}',
        },
        closed: {
          thank_you: 'Sara Alert اكتملت مرمتابعة %{initials_age} في %{completed_date}! أشكركم على مشاركتكم.',
        },
      },
      voice: {
        intro: 'مرحبًا، هذه سارة، مساعدة الصحة العامة الآلية التي تطلب تقريرك اليومي.',
        initials_age: '%{initials} ، %{age} سنة',
        daily: 'هذا التقرير عن: %{names}. %{experiencing_symptoms}. الرجاء الرد بـ "نعم" أو "لا"',
        try_again: 'أنا آسف لم أفهم. لنجرب مجددا.',
        thanks: 'شكرا لاستكمال تقريرك اليومي! مع السلامة.',
      },
    },
    symptoms: {
      chills: {
        name: 'قشعريرة',
      },
      'congestion-or-runny-nose': {
        name: 'احتقان أو سيلان الأنف',
      },
      cough: {
        name: 'سعال',
      },
      diarrhea: {
        name: 'إسهال',
      },
      'difficulty-breathing': {
        name: 'صعوبة في التنفس',
      },
      fatigue: {
        name: 'تعب',
      },
      fever: {
        name: 'حمى',
        notes: 'قياس درجة الحرارة يساوي أو يزيد ١100.4°F/38°C.٤ درجة فهرنهايت/٣٨ درجة مئوية',
      },
      headache: {
        name: 'صداع',
      },
      'muscle-pain': {
        name: 'ألم عضلي',
      },
      'nausea-or-vomiting': {
        name: 'غثيان أو تقيؤ',
      },
      'new-loss-of-smell': {
        name: 'فقدان حاسة الشم المفاجئ',
      },
      'new-loss-of-taste': {
        name: 'فقدان حاسة التذوق المفاجئ',
      },
      'pulse-ox': {
        name: 'مقياس التأكسج النبضي',
        notes: 'ما هو أقل مستوى أكسجين لديك في ال 24 ساعة الماضية؟',
      },
      'repeated-shaking-with-chills': {
        name: 'قشعريرة',
      },
      'shortness-of-breath': {
        name: 'ضيق التنفس',
      },
      'sore-throat': {
        name: 'التهاب الحلق',
      },
      temperature: {
        name: 'درجة الحرارة',
        notes: 'الرجاء إدخال درجة حرارتك الحالية بالدرجات فهرنهايت',
      },
      'used-a-fever-reducer': {
        name: 'أستخدمت مخفض الحمى',
        notes: 'في ال 24 ساعة الماضية، هل استعملت أي دواء يقلل من الحمى؟',
      },
      other: {
        name: 'أخرى',
        notes: 'أود أن يتصل بي أحدهم لمتابعة أعراض أخرى أو إحتياجات إضافية',
      },
      'no-symptoms': 'لا أعاني من أي أعراض',
    },
    'threshold-op': {
      'less-than': 'أصغر من',
      'less-than-or-equal': 'أصغر من أو تساوي',
      'greater-than': 'أكبر من',
      'greater-than-or-equal': 'أكبر أو يساوي',
      equal: 'يساوي',
      'not-equal': 'لا تساوي',
    },
  },
  zho: {
    html: {
      shared: {
        email: '电子邮件',
        phone: '电话',
        webpage: '网页',
      },
      weblink: {
        title: '日常自我报告 ',
        'bool-title': '请选择您正经历的所有症状',
        instruction1: '如果您没有报告任何症状，请继续遵循由当地卫生部门提供的建议。',
        instruction2:
          '如果您报告了任何症状，当地卫生部门将会尽快与您联系。如果您有任何紧急问题，请联系您的医疗服务提供者或当地卫生部门。避免与其他人密切接触，并留在家中。',
        instruction3: '如果您遇到紧急医疗情况，请拨打911，并让他们知道你正在接受卫生部门的监控。',
        instruction4: '请使用下面的联系信息与负责您病例的公共健康官员联系。',
        submit: '提交',
        thank_you: '感谢您完成您的自我报告',
      },
      email: {
        shared: {
          greeting: '亲爱的%{name},',
          report: '每日报告',
          footer:
            '不要回复此电子邮件，转发此电子邮件或分享此链接。此消息是由Sara Alert系统自动生成的，并且是唯一的，仅供您使用。如果您希望停止接收这些通知，或者认为这是一个错误，请联系您当地的公共卫生部门。 有关隐私和更多信息，请访问saraalert.org。',
        },
        enrollment: {
          subject: '加入Sara Alert',
          header: '欢迎使用Sara Alert系统',
          info1: '您已加入Sara Alert监控系统。我们要求您提供您的每日状况报告。请单击下面的按钮，然后按照屏幕上的说明进行操作。',
          info2: '您将每天收到了类似的提醒，直到你的监控期结束。',
        },
        reminder: {
          subject: 'Sara Alert报告提醒',
          header: '这封邮件提醒您完成您的每日报告',
          thank_you: '感谢您参加Sara Alert监控系统，请使用下面的链接填写您的每日报告。',
        },
        closed: {
          subject: 'Sara Alert监控期已结束',
          header: '监控已完成！',
          thank_you: 'Sara警报监控 %{initials_age}已于%{completed_date}完成！感谢您的参与。',
        },
        contact: {
          info1: '如果您有任何疑问，请使用下面的联系信息联系帮助您的公共卫生机构：',
          info2: '请联系帮助您加入Sara Alert 系统的公共卫生机构。',
        },
      },
    },
    twilio: {
      shared: {
        experiencing_symptoms_s: '%{name}是否正经历任何以下症状: %{symptom_names}.',
        experiencing_symptoms_p: '这些人是否正经历任何以下症状: %{symptom_names}.',
        max_retries_message: '抱歉，您已达到最大响应尝试次数。如果您遇到医疗紧急情况，请致电911。',
      },
      sms: {
        prompt: {
          intro: '欢迎使用Sara Alert系统。我们会将%{name}每日报告发送到这个电话号码。有关保护隐私和更多信息，请访问saraalert.org。',
          reminder: '这是Sara Alert系统提醒您请回复我们的每日报告信息',
          name: '%{name}',
          daily: '这是Sara Alert的每日报告: %{names}. %{experiencing_symptoms} 请用“是”或“否”回答',
          try_again: '对不起，我听不懂。请回答“是”或“否”。如有任何疑问，请联系当地的卫生部门。',
          thanks: '感谢您填写每日报告',
        },
        weblink: {
          intro: '请填写Sara Alert每日报告 %{initials_age}: %{url}',
        },
        closed: {
          thank_you: 'Sara警报监控 %{initials_age}已于%{completed_date}完成！感谢您的参与。',
        },
      },
      voice: {
        intro: '您好，这里是自动公共卫生助手Sara打电话询问您的每日报告。',
        initials_age: '%{initials}，年龄%{age}',
        daily: '这个报告是有关: %{names}. %{experiencing_symptoms}. 请用“是”或“否”回答',
        try_again: '对不起，我听不懂。让我们再试一次。',
        thanks: '感谢您完成您的每日报告！再见。',
      },
    },
    symptoms: {
      chills: {
        name: '发冷',
      },
      'congestion-or-runny-nose': {
        name: '拥堵或流鼻涕',
      },
      cough: {
        name: '咳嗽',
      },
      diarrhea: {
        name: '腹泻',
      },
      'difficulty-breathing': {
        name: '呼吸困难',
      },
      fatigue: {
        name: '疲劳',
      },
      fever: {
        name: '发烧',
        notes: '发热或测量体温温度等于或高于100.4华氏度/38摄氏度',
      },
      headache: {
        name: '头痛',
      },
      'muscle-pain': {
        name: '肌肉疼痛',
      },
      'nausea-or-vomiting': {
        name: '恶心或呕吐',
      },
      'new-loss-of-smell': {
        name: '新的嗅觉丧失',
      },
      'new-loss-of-taste': {
        name: '新的味觉丧失',
      },
      'pulse-ox': {
        name: '脉搏血氧水平',
        notes: '你过去24小时里最低的氧气水平是多少？',
      },
      'repeated-shaking-with-chills': {
        name: '反复发冷颤抖',
      },
      'shortness-of-breath': {
        name: '呼吸急促',
      },
      'sore-throat': {
        name: '咽喉痛',
      },
      temperature: {
        name: '温度',
        notes: '请输入您当前的温度（华氏度）',
      },
      'used-a-fever-reducer': {
        name: '使用退烧药',
        notes: '過去24小時，你有沒有服用任何能減少發熱的藥物？',
      },
      other: {
        name: '其它',
        notes: '我希望有人打电话给我跟进其它症状或其它需求',
      },
      'no-symptoms': '我沒有出現任何症狀',
    },
    'threshold-op': {
      'less-than': '小于',
      'less-than-or-equal': '小于或等于',
      'greater-than': '大于',
      'greater-than-or-equal': '大于或等于',
      equal: '等于',
      'not-equal': '不等于',
    },
  },
};

export { mockTranslations };
