const mockTranslations = {
  'en': {
    'symptoms': {
      'cough': {
        'name': 'Cough',
        'notes': ''
      },
      'difficulty_breathing': {
        'name': 'Difficulty Breathing',
        'notes': ''
      },
      'fever': {
        'name': 'Fever',
        'notes': 'Feeling feverish or have a measured temperature at or above 100.4°F/38°C'
      },
      'used_a_fever_reducer': {
        'name': 'Used A Fever Reducer',
        'notes': 'In the past 24 hours, have you used any medicine that reduces fevers?'
      },
      'chills': {
        'name': 'Chills',
        'notes': ''
      },
      'repeated_shaking_with_chills': {
        'name': 'Repeated Shaking with Chills',
        'notes': ''
      },
      'muscle_pain': {
        'name': 'Muscle Pain',
        'notes': ''
      },
      'headache': {
        'name': 'Headache',
        'notes': ''
      },
      'sore_throat': {
        'name': 'Sore Throat',
        'notes': ''
      },
      'new_loss_of_taste_or_smell': {
        'name': 'New Loss of Taste or Smell',
        'notes': ''
      },
      'pulse_ox': {
        'name': 'Pulse Ox',
        'notes': 'What was your lowest oxygen level in the past 24 hours?'
      },
      'fatigue': {
        'name': 'Fatigue',
        'notes': ''
      },
      'nausea_or_vomiting': {
        'name': 'Nausea Or Vomiting',
        'notes': ''
      },
      'diarrhea': {
        'name': 'Diarrhea',
        'notes': ''
      },
      'nasal_congestion': {
        'name': 'Nasal Congestion',
        'notes': ''
      },
      'runny_nose': {
        'name': 'Runny Nose',
        'notes': ''
      },
      'temperature': {
        'name': 'Temperature',
        'notes': 'Please enter your current temperature in degrees Fahrenheit'
      },
      'other': {
        'name': 'Other',
        'notes': 'I would like someone to call me to follow-up on other symptoms or additional needs'
      },
      'no_symptoms': 'I am not experiencing any symptoms',
      'new_loss_of_smell': {
        'name': 'New Loss of Smell',
        'notes': ''
      },
      'new_loss_of_taste': {
        'name': 'New Loss of Taste',
        'notes': ''
      },
      'shortness_of_breath': {
        'name': 'Shortness of Breath',
        'notes': ''
      },
      'congestion_or_runny_nose': {
        'name': 'Congestion or Runny Nose',
        'notes': ''
      }
    },
    'threshold-op': {
      'less-than': 'Less Than',
      'less-than-or-equal': 'Less Than Or Equal to',
      'greater-than': 'Greater Than',
      'greater-than-or-equal': 'Greater Than Or Equal to',
      'equal': 'Equal to',
      'not-equal': 'Not Equal to'
    },
    'web': {
      'title': 'Daily Self-Report',
      'bool-title': 'Please select all symptoms which you are experiencing.',
      'submit': 'Submit',
      'thank-you': 'Thank You For Completing Your Self Report',
      'instruction1': 'If you did not report any symptoms, please continue to follow the recommendations provided by your local health department.',
      'instruction2': 'If you reported any symptoms, your local health department will be reaching out soon. If you have any immediate concerns, please contact your medical provider or local health department. Avoid close contact with other people and stay at home.',
      'instruction3': 'If you are experiencing a medical emergency, please call 911 and let them know you are being monitored by the health department.',
      'instruction4': 'Please use the contact information below to get into contact with a public health official managing your case.',
      'email': 'Email',
      'phone': 'Phone',
      'webpage': 'Webpage'
    },
    'email': {
      'reminder': {
        'subject': 'Sara Alert Report Reminder',
        'header': 'This is your reminder to complete your daily report.',
        'dear': 'Dear',
        'thank-you': 'Thank you for participating in the Sara Alert monitoring program, please fill out your daily report using the link below.',
        'report': 'Daily Report',
        'footer': 'Do not reply to this email, forward this email, or share this link. This message was automatically generated by the Sara Alert system and is unique and intended only for you. If you wish to stop receiving these notifications or believe that it was a mistake, please contact your local public health department. For privacy and more info, visit saraalert.org.'
      },
      'enrollment': {
        'subject': 'Sara Alert Enrollment',
        'header': 'Welcome to the Sara Alert System!',
        'dear': 'Dear',
        'info1': 'You have been enrolled in the Sara Alert monitoring system. We ask that you provide daily reports of your status. Simply click the button below and follow the on-screen instructions.',
        'info2': 'You will receive a similar reminder daily until your monitoring period has ended. If you have any questions please reach out to the public health organization that helped enroll you.',
        'report': 'Daily Report',
        'footer': 'Do not reply to this email, forward this email, or share this link. This message was automatically generated by the Sara Alert system and is unique and intended only for you. If you wish to stop receiving these notifications or believe that it was a mistake, please contact your local public health department. For privacy and more info, visit saraalert.org.'
      },
      'closed': {
        'subject': 'Sara Alert Reporting Complete',
        'header': 'Monitoring complete!',
        'dear': 'Dear',
        'thank-you': 'Your Sara Alert monitoring is now complete! Thank you for your participation.',
        'footer': 'Do not reply to this email, forward this email, or share this link. This message was automatically generated by the Sara Alert system and is unique and intended only for you. If you wish to stop receiving these notifications or believe that it was a mistake, please contact your local public health department. For privacy and more info, visit saraalert.org.'
      }
    },
    'sms': {
      'prompt': {
        'intro1': 'Welcome to the Sara Alert system, we will be sending your daily reports for',
        'intro2': 'to this phone number. For privacy and more info, visit saraalert.org.',
        'reminder': 'This is the Sara Alert system reminding you to please reply to our daily-report messages.',
        'daily1': 'This is the Sara Alert daily report for: ',
        'daily2-p': ' Are any of these people ',
        'daily2-s': ' Is this person ',
        'daily3': 'experiencing any of the following symptoms: ',
        'daily4': ' Please reply with \'Yes\' or \'No\'',
        'try-again': `I'm sorry, I didn't quite get that. Please reply with \'Yes\' or \'No\'. If you have any questions, please contact your local health department.`,
        'max_retries_message': 'I’m sorry, you have reached the maximum number of response attempts. If you are experiencing a medical emergency, please call 911.',
        'thanks': 'Thank you for completing your daily report!'
      },
      'weblink': {
        'intro': 'Please complete the Sara Alert Daily Report for'
      }
    },
    'phone': {
      'intro': 'Hello, this is Sara, the automated public health assistant calling for your daily report.',
      'try-again': `I'm sorry, I didn't quite get that. Let's try again.`,
      'max_retries_message': 'I’m sorry, you have reached the maximum number of response attempts. If you are experiencing a medical emergency, please call 911.',
      'thanks': 'Thank you for completing your daily report! Goodbye.',
      'age': 'Age',
      'daily1': ' This is the report for: ',
      'daily2-p': ' Are any of these people ',
      'daily2-s': ' Is this person ',
      'daily3': ' experiencing any of the following symptoms ',
      'daily4': ' Please reply with \'Yes\' or \'No\''
    }
  },
  'es': {
    'symptoms': {
      'cough': {
        'name': 'Tos',
        'notes': ''
      },
      'difficulty_breathing': {
        'name': 'Problemas para respirar',
        'notes': ''
      },
      'fever': {
        'name': 'Fiebre',
        'notes': 'Si siente que tiene fiebre o tiene una temperatura igual o superior a 100.4°F/38°C'
      },
      'used_a_fever_reducer': {
        'name': 'Tomó medicina para reducir la fiebre',
        'notes': 'En las últimas 24 horas, ¿ha tomado algún medicamento para reducir la fiebre?'
      },
      'chills': {
        'name': 'Escalofrío',
        'notes': ''
      },
      'repeated_shaking_with_chills': {
        'name': 'Tiembla repetidamente y tiene escalofríos',
        'notes': ''
      },
      'muscle_pain': {
        'name': 'Dolor muscular',
        'notes': ''
      },
      'headache': {
        'name': 'Dolor de cabeza',
        'notes': ''
      },
      'sore_throat': {
        'name': 'Dolor de garganta',
        'notes': ''
      },
      'new_loss_of_taste_or_smell': {
        'name': 'Perdió recientemente el sentido del olfato y de gusto',
        'notes': ''
      },
      'pulse_ox': {
        'name': 'oxímetro de pulso',
        'notes': 'Ingrese la lectura más baja del oxímetro de pulso en las últimas 24 horas'
      },
      'fatigue': {
        'name': 'Fatiga',
        'notes': ''
      },
      'nausea_or_vomiting': {
        'name': 'Náuseas o vómitos',
        'notes': ''
      },
      'diarrhea': {
        'name': 'Diarrea',
        'notes': ''
      },
      'nasal_congestion': {
        'name': 'Congestión nasal',
        'notes': ''
      },
      'runny_nose': {
        'name': 'Exceso de moco en la nariz',
        'notes': ''
      },
      'temperature': {
        'name': 'Temperatura',
        'notes': 'Por favor ingrese su temperatura actual en grados Fahrenheit'
      },
      'other': {
        'name': 'Otro',
        'notes': 'Me gustaría que alguien me llamara para hacer un seguimiento de otros síntomas o necesidades adicionales'
      },
      'no_symptoms': 'No tengo ningún síntoma.',
      'new_loss_of_smell': {
        'name': 'Pérdida reciente el olfato',
        'notes': ''
      },
      'new_loss_of_taste': {
        'name': 'Pérdida reciente del gusto',
        'notes': ''
      },
      'shortness_of_breath': {
        'name': 'Falta de aire',
        'notes': ''
      },
      'congestion_or_runny_nose': {
        'name': 'Congestión nasal o un exceso de moco en la nariz',
        'notes': ''
      }
    },
    'threshold-op': {
      'less-than': 'Menos que',
      'less-than-or-equal': 'Menor o igual a',
      'greater-than': 'Mas grande que',
      'greater-than-or-equal': 'Mayor que o igual a',
      'equal': 'Igual a',
      'not-equal': 'no es igual a'
    },
    'web': {
      'title': 'Reporte diario',
      'bool-title': 'Por favor, seleccione los síntomas que está sintiendo actualmente.',
      'submit': 'Enviar',
      'thank-you': '\'¡Gracias por completar su informe diario!',
      'instruction1': 'Si Usted no reportó ningún síntoma, por favor siga las recomendaciones proveídas por su departamento de salud local.',
      'instruction2': 'Si Usted reportó algún síntoma, su departamento de salud local se comunicará pronto con Usted. Si tiene alguna inquietud inmediata, llame a su proveedor médico o al departamento de salud local. Evite el contacto cercano con otras personas y quédese en casa por favor.',
      'instruction3': 'Si tiene una emergencia médica, por favor llame al 911 e infórmeles que el departamento de salud lo está monitoreando.',
      'instruction4': 'Por favor utilice la información de contacto a continuación para ponerse en contacto con un funcionario de salud pública que esté a cargo de su caso',
      'email': 'Correo electrónico',
      'phone': 'Teléfono',
      'webpage': 'Página web'
    },
    'email': {
      'reminder': {
        'subject': 'Recordatorio del reporte de Sara Alert',
        'header': 'Recordatorio del reporte de Sara Alert',
        'dear': 'Estimado/a',
        'thank-you': 'Gracias por participar en el programa de monitoreo de Sara Alert. Favor de completar su informe diario utilizando el siguiente enlace.',
        'report': 'Reporte diario',
        'footer': 'No responda o reenvíe este correo electrónico, ni comparta este enlace. Este mensaje fue generado automáticamente por el sistema Sara Alert y es único y está destinado solo para usted. Si desea dejar de recibir estas notificaciones o piensa que fue un error, por favor pónganse en contacto con su departamento de salud pública local. Para privacidad y más información, visite saraalert.org.'
      },
      'enrollment': {
        'subject': 'Inscripción de Sara Alert',
        'header': 'Bienvenido al sistema Sara Alert',
        'dear': 'Estimado/a',
        'info1': 'Usted ha sido inscrito en el sistema de monitoreo Sara Alert. Le pedimos que proporcione informes diarios de su estado de salud. Simplemente haga clic en el botón a continuación y siga las instrucciones en pantalla.',
        'info2': 'Usted recibirá un recordatorio diario similar hasta que finalice su período de monitoreo. Si tiene alguna pregunta, por favor pónganse en contacto con el proveedor de atención médica que le ayudó a inscribirse.',
        'report': 'Reporte diario',
        'footer': 'No responda o reenvíe este correo electrónico, ni comparta este enlace. Este mensaje fue generado automáticamente por el sistema Sara Alert y es único y está destinado solo para usted. Si desea dejar de recibir estas notificaciones o piensa que fue un error, por favor pónganse en contacto con su departamento de salud pública local. Para privacidad y más información, visite saraalert.org.'
      },
      'closed': {
        'subject': 'Reporte de Sara Alert completo',
        'header': 'Reporte de Sara Alert completo',
        'dear': 'Estimado/a',
        'thank-you': '¡Su reporte de Sara Alert está completo! Gracias por su participación.',
        'footer': 'No responda o reenvíe este correo electrónico, ni comparta este enlace. Este mensaje fue generado automáticamente por el sistema Sara Alert y es único y está destinado solo para usted. Si desea dejar de recibir estas notificaciones o piensa que fue un error, por favor pónganse en contacto con su departamento de salud pública local. Para privacidad y más información, visite saraalert.org.'
      }
    },
    'sms': {
      'prompt': {
        'intro1': 'Bienvenido al sistema Sara Alert, le enviaremos sus reportes diarios para',
        'intro2': 'a este número de teléfono. Para privacidad y más información, visite saraalert.org.',
        'reminder': 'Este es el sistema Sara Alert recordándole que por favor responda a nuestros mensajes de reporte diario.',
        'daily1': 'Este es el informe diario de Sara Alert para: ',
        'daily2-p': ' ¿Esta alguna de estas personas ',
        'daily2-s': ' ¿Está usted ',
        'daily3': 'sintiendo uno o mas de los siguientes síntomas hoy?: ',
        'daily4': ' Responda con \'Sí\' o \'No\'',
        'try-again': 'Lo siento, no entendí. Responda con \'Sí\' o \'No\'',
        'max_retries_message': 'Lo siento, ha alcanzado el número máximo de intentos de respuesta. Si tiene una emergencia médica, llame al 911.',
        'thanks': '¡Gracias por completar su informe diario!'
      },
      'weblink': {
        'intro': 'Complete el Informe diario de Sara Alert para'
      }
    },
    'phone': {
      'intro': 'Hola, soy Sara, la asistente de salud pública automatizada que solicita su informe diario.',
      'try-again': 'Lo siento, no entendí. Intentemoslo de nuevo.',
      'max_retries_message': 'Lo siento, ha alcanzado el número máximo de intentos de respuesta. Si tiene una emergencia médica, llame al 911.',
      'thanks': '¡Gracias por completar su informe diario! Adiós.',
      'age': 'años',
      'daily1': ' Este es el informe diario de Sara Alert para: ',
      'daily2-p': ' ¿Esta alguna de estas personas ',
      'daily2-s': ' ¿Está usted ',
      'daily3': ' sintiendo uno o mas de los siguientes síntomas hoy? ',
      'daily4': ' Responda con \'Sí\' o \'No\''
    }
  },
  'es-PR': {
    'symptoms': {
      'cough': {
        'name': 'Tos',
        'notes': ''
      },
      'difficulty_breathing': {
        'name': 'Problemas para respirar',
        'notes': ''
      },
      'fever': {
        'name': 'Fiebre',
        'notes': 'Se siente que tiene fiebre o tiene una temperatura igual o superior a 100.4°F/38°C'
      },
      'used_a_fever_reducer': {
        'name': 'Tomó medicina para reducir la fiebre',
        'notes': 'En las últimas 24 horas, ¿ha tomado algún medicamento para reducir la fiebre?'
      },
      'chills': {
        'name': 'Escalofrío',
        'notes': ''
      },
      'repeated_shaking_with_chills': {
        'name': 'Tiembla repetidamente y tiene escalofríos',
        'notes': ''
      },
      'muscle_pain': {
        'name': 'Dolor muscular',
        'notes': ''
      },
      'headache': {
        'name': 'Dolor de cabeza',
        'notes': ''
      },
      'sore_throat': {
        'name': 'Dolor de garganta',
        'notes': ''
      },
      'new_loss_of_taste_or_smell': {
        'name': 'Perdió recientemente el sentido del olfato y de gusto',
        'notes': ''
      },
      'pulse_ox': {
        'name': 'oxímetro de pulso',
        'notes': 'Ingrese la lectura más baja del oxímetro de pulso en las últimas 24 horas'
      },
    'fatigue': {
        'name': 'Fatiga',
        'notes': ''
      },
      'nausea_or_vomiting': {
        'name': 'Náuseas o vómitos',
        'notes': ''
      },
      'diarrhea': {
        'name': 'Diarrea',
        'notes': ''
      },
      'nasal_congestion': {
        'name': 'Congestión nasal',
        'notes': ''
      },
      'runny_nose': {
        'name': 'Exceso de moco en la nariz',
        'notes': ''
      },
      'temperature': {
        'name': 'Temperatura',
        'notes': 'Por favor ingrese su temperatura actual en grados Fahrenheit'
      },
      'other': {
        'name': 'Otro',
        'notes': 'Me gustaría que alguien me llamara para hacer un seguimiento de otros síntomas o necesidades adicionales'
      },
      'no_symptoms': 'No tengo ningún síntoma.',
      'new_loss_of_smell': {
        'name': 'Pérdida reciente el olfato',
        'notes': ''
      },
      'new_loss_of_taste': {
        'name': 'Pérdida reciente del gusto',
        'notes': ''
      },
      'shortness_of_breath': {
        'name': 'Falta de aire',
        'notes': ''
      },
      'congestion_or_runny_nose': {
        'name': 'Congestión nasal o un exceso de moco en la nariz',
        'notes': ''
      }
    },
    'threshold-op': {
      'less-than': 'Menos que',
      'less-than-or-equal': 'Menor o igual a',
      'greater-than': 'Mas grande que',
      'greater-than-or-equal': 'Mayor que o igual a',
      'equal': 'Igual a',
      'not-equal': 'no es igual a'
    },
    'web': {
      'title': 'Reporte diario',
      'bool-title': 'Por favor, seleccione los síntomas que está sintiendo actualmente.',
      'submit': 'Enviar',
      'thank-you': '\'¡Gracias por completar su informe diario!',
      'instruction1': 'Si Usted no reportó ningún síntoma, por favor siga las recomendaciones provistas por su departamento de salud local.',
      'instruction2': 'Si Usted reportó algún síntoma, su departamento de salud local se comunicará pronto con Usted. Si tiene alguna inquietud inmediata, llame a su proveedor médico o al departamento de salud local. Evite el contacto cercano con otras personas y quédese en casa por favor.',
      'instruction3': 'Si tiene una emergencia médica, por favor llame al 911 e infórmeles que el departamento de salud lo está monitoreando.',
      'instruction4': 'Por favor utilice la información de contacto a continuación para ponerse en contacto con un funcionario de salud pública que esté a cargo de su caso.',
      'email': 'Correo electrónico',
      'phone': 'Teléfono',
      'webpage': 'Página web'
    },
    'email': {
      'reminder': {
        'subject': 'Recordatorio del reporte de Sara Alert',
        'header': 'Recordatorio del reporte de Sara Alert',
        'dear': 'Estimado/a',
        'thank-you': 'Gracias por participar en el programa de monitoreo de Sara Alert. Favor de completar su informe diario utilizando el siguiente enlace.',
        'report': 'Reporte diario',
        'footer': 'No responda o reenvíe este correo electrónico, ni tampoco comparta este enlace. Este mensaje fue generado automáticamente por el sistema Sara Alert y es único y está destinado solo para usted. Si desea dejar de recibir estas notificaciones o piensa que fue un error, por favor pónganse en contacto con su departamento de salud pública local. Para privacidad y más información, visite saraalert.org.'
      },
      'enrollment': {
        'subject': 'Inscripción de Sara Alert',
        'header': 'Bienvenido al sistema Sara Alert',
        'dear': 'Estimado/a',
        'info1': 'Usted ha sido inscrito en el sistema de monitoreo Sara Alert. Le pedimos que proporcione informes diarios de su estado de salud. Simplemente haga clic en el botón a continuación y siga las instrucciones en pantalla.',
        'info2': 'Usted recibirá un recordatorio diario similar hasta que finalice su período de monitoreo. Si tiene alguna pregunta, por favor pónganse en contacto con el proveedor de atención médica que le ayudó a inscribirse.',
        'report': 'Reporte diario',
        'footer': 'No responda o reenvíe este correo electrónico, ni tampoco comparta este enlace. Este mensaje fue generado automáticamente por el sistema Sara Alert y es único y está destinado solo para usted. Si desea dejar de recibir estas notificaciones o piensa que fue un error, por favor pónganse en contacto con su departamento de salud pública local. Para privacidad y más información, visite saraalert.org.'
      },
      'closed': {
        'subject': 'Reporte de Sara Alert completo',
        'header': 'Reporte de Sara Alert completo',
        'dear': 'Estimado/a',
        'thank-you': '¡Su reporte de Sara Alert está completo! Gracias por su participación.',
        'footer': 'No responda o reenvíe este correo electrónico, ni tampoco comparta este enlace. Este mensaje fue generado automáticamente por el sistema Sara Alert y es único y está destinado solo para usted. Si desea dejar de recibir estas notificaciones o piensa que fue un error, por favor pónganse en contacto con su departamento de salud pública local. Para privacidad y más información, visite saraalert.org.'
      }
    },
    'sms': {
      'prompt': {
        'intro1': 'Bienvenido al sistema Sara Alert, le enviaremos sus reportes diarios para',
        'intro2': 'a este número de teléfono. Para privacidad y más información, visite saraalert.org.',
        'reminder': 'Este es el sistema Sara Alert recordándole que por favor responda a nuestros mensajes de reporte diario.',
        'daily1': 'Este es el informe diario de Sara Alert para: ',
        'daily2-p': ' ¿Esta alguna de estas personas ',
        'daily2-s': ' ¿Está usted ',
        'daily3': 'sintiendo uno o más de los siguientes síntomas hoy?: ',
        'daily4': ' Responda con \'Sí\' o \'No\'',
        'try-again': 'Lo siento, no entendí. Responda con \'Sí\' o \'No\'',
        'max_retries_message': 'Lo siento, ha alcanzado el número máximo de intentos de respuesta. Si tiene una emergencia médica, llame al 911.',
        'thanks': '¡Gracias por completar su informe diario!'
      },
      'weblink': {
        'intro': 'Complete el Informe diario de Sara Alert para'
      }
    },
    'phone': {
      'intro': 'Hola, soy Sara, la asistente de salud pública automatizada que solicita su informe diario.',
      'try-again': 'Lo siento, no entendí. Intentemoslo de nuevo.',
      'max_retries_message': 'Lo siento, ha alcanzado el número máximo de intentos de respuesta. Si tiene una emergencia médica, llame al 911.',
      'thanks': '¡Gracias por completar su informe diario! Adiós.',
      'age': 'años',
      'daily1': ' Este es el informe diario de Sara Alert para: ',
      'daily2-p': ' ¿Esta alguna de estas personas ',
      'daily2-s': ' ¿Está usted ',
      'daily3': ' sintiendo uno o más de los siguientes síntomas hoy? ',
      'daily4': ' Responda con \'Sí\' o \'No\''
    }
  },
  'fr': {
    'symptoms': {
      'cough': {
        'name': 'Toux',
        'notes': ''
      },
      'difficulty_breathing': {
        'name': 'Difficultés respiratoires',
        'notes': ''
      },
      'fever': {
        'name': 'Fièvre',
        'notes': 'Sensation de fébrilité ou température mesurée supérieure ou égale à 38 °C (100,4 °F)'
      },
      'used_a_fever_reducer': {
        'name': 'Utilisation d’un agent pour diminuer la fièvre',
        'notes': 'Avez_vous utilisé un médicament pour diminuer la fièvre au cours des dernières 24 heures?'
      },
      'chills': {
        'name': 'Frissons',
        'notes': ''
      },
      'repeated_shaking_with_chills': {
        'name': 'Tremblements répétés accompagnés de frissons',
        'notes': ''
      },
      'muscle_pain': {
        'name': 'Douleurs musculaires',
        'notes': ''
      },
      'headache': {
        'name': 'Maux de tête',
        'notes': ''
      },
      'sore_throat': {
        'name': 'Maux de gorge',
        'notes': ''
      },
      'new_loss_of_taste_or_smell': {
        'name': `Une nouvelle perte de goût ou de l'odorat`,
        'notes': ''
      },
      'pulse_ox': {
        'name': 'd’oxymétrie de pouls',
        'notes': 'Saisissez votre mesure d’oxymétrie de pouls la plus faible au cours des dernières 24 heures'
      },
      'fatigue': {
        'name': 'Fatigue',
        'notes': ''
      },
      'nausea_or_vomiting': {
        'name': 'Nausées ou vomissements',
        'notes': ''
      },
      'diarrhea': {
        'name': 'Diarrhée',
        'notes': ''
      },
      'nasal_congestion': {
        'name': 'Congestion nasale',
        'notes': ''
      },
      'runny_nose': {
        'name': 'Nez qui coule',
        'notes': ''
      },
      'temperature': {
        'name': 'Température',
        'notes': 'Veuillez entrer votre température actuelle en degrés Fahrenheit'
      },
      'other': {
        'name': 'Other',
        'notes': `J'aimerais que quelqu'un m'appelle pour faire le suivi d'autres symptômes ou d’autre chose`
      },
      'no_symptoms': 'Aucun symptôme',
      'new_loss_of_smell': {
        'name': 'Nouvelle perte de l’odorat',
        'notes': ''
      },
      'new_loss_of_taste': {
        'name': 'Nouvelle perte de goût',
        'notes': ''
      },
      'shortness_of_breath': {
        'name': 'Essoufflement',
        'notes': ''
      },
      'congestion_or_runny_nose': {
        'name': 'Congestion nasale ou nez qui coule',
        'notes': ''
      }
    },
    'threshold_op': {
      'less-than': 'moins que',
      'less-than-or-equal': 'inférieur ou égal à',
      'greater-than': 'plus grand que',
      'greater-than-or-equal': 'Plus grand ou égal à',
      'equal': 'égal à',
      'not-equal': 'pas égal à'
    },
    'web': {
      'title': 'Rapport quotidien',
      'bool-title': 'Veuillez sélectionner tous les symptômes que vous présentez.',
      'submit': 'Envoyer',
      'thank-you': 'Merci d’avoir complété votre rapport quotidien !',
      'instruction1': `Si vous n'avez pas signalé aucun symptôme, veuillez continuer à suivre les recommandations fournies par votre autorité de santé publique locale.`,
      'instruction2': 'Si vous signalez des symptômes, votre autorité de santé publique locale vous contactera bientôt. Si vous avez des inquiétudes immédiates, veuillez contacter votre fournisseur médical ou votre autorité de santé publique locale. Évitez vos contacts avec les autres et vous devez vous isoler à la maison.',
      'instruction3': 'En cas d’urgence médicale, appelez le 911, et faites-leur savoir que vous êtes surveillé par le autorité de santé publique.',
      'instruction4': 'Veuillez utiliser les coordonnées ci-dessous si vous souhaitez nous contacter au sujet de votre cas.',
      'email': 'Courriel',
      'phone': 'Téléphone',
      'webpage': 'Site web'
    },
    'email': {
      'reminder': {
        'subject': 'Rappel de rapport d’Alerte Sara',
        'header': 'Rappel de rapport d’Alerte Sara',
        'dear': 'Cher/Chère',
        'thank-you': 'Merci de participer au programme de surveillance d’Alerte Sara. Veuillez remplir votre rapport quotidien en utilisant le lien ci-dessous.',
        'report': 'Rappel de rapport d’Alerte Sara',
        'footer': 'Ne répondez pas à cet e-mail, ne le transférez pas et ne partagez pas ce lien avec quiconque. Ce message a été généré automatiquement par le système d’Alerte Sara ; il est unique et n’est destiné qu’à vous. Si vous souhaitez cesser de recevoir ces notifications ou si vous pensez qu’il s’agit d’une erreur, veuillez contacter les autorités sanitaires locales. Pour la confidentialité et plus d’informations, visitez saraalert.org.'
      },
      'enrollment': {
        'subject': 'Recrutement pour alerte Sara',
        'header': 'Bienvenue sur le système d’Alerte Sara',
        'dear': 'Cher/Chère',
        'info1': 'Vous avez été recruté(e) dans le système de surveillance d’Alerte Sara. Nous vous demandons de fournir des rapports quotidiens sur votre état. Veuillez cliquer sur le bouton ci-dessous et suivre les instructions qui s’affichent à l’écran.',
        'info2': 'Vous recevrez un rappel similaire tous les jours jusqu’à ce que votre période de surveillance soit terminée. Si vous avez des questions, veuillez contacter le professionnel de santé qui vous a recruté(e).',
        'report': 'Rapport quotidien',
        'footer': 'Ne répondez pas à cet e-mail, ne le transférez pas et ne partagez pas ce lien avec quiconque. Ce message a été généré automatiquement par le système d’Alerte Sara ; il est unique et n’est destiné qu’à vous. Si vous souhaitez cesser de recevoir ces notifications ou si vous pensez qu’il s’agit d’une erreur, veuillez contacter les autorités sanitaires locales. Pour la confidentialité et plus d’informations, visitez saraalert.org.'
      },
      'closed': {
        'subject': 'Rapport d’Alerte Sara complété',
        'header': 'Rapport d’Alerte Sara complété',
        'dear': 'Cher/Chère',
        'thank-you': 'Votre surveillance d’Alerte Sara est maintenant terminée ! Merci pour votre participation.',
        'footer': 'Ne répondez pas à cet e-mail, ne le transférez pas et ne partagez pas ce lien avec quiconque. Ce message a été généré automatiquement par le système d’Alerte Sara ; il est unique et n’est destiné qu’à vous. Si vous souhaitez cesser de recevoir ces notifications ou si vous pensez qu’il s’agit d’une erreur, veuillez contacter les autorités sanitaires locales. Pour la confidentialité et plus d’informations, visitez saraalert.org.'
      }
    },
    'sms': {
      'prompt': {
        'intro1': 'Bienvenue sur le système d’Alerte Sara, nous vous enverrons vos rapports quotidiens pour',
        'intro2': 'à ce numéro de téléphone. Pour la confidentialité et plus d’informations, visitez saraalert.org.',
        'reminder': 'Ceci est un rappel du système d’Alerte Sara vous rappelant que vous devez répondre à nos messages de rapport quotidien.',
        'daily1': 'Il s’agit d’un rapport d’alerte Sara quotidien destiné aux: ',
        'daily2-p': ' Parmi ces personnes ',
        'daily2-s': ' Cette personne est-elle ',
        'daily3': ' y en a-t-il qui présentent un des symptômes suivants: ',
        'daily4': ' Veuillez répondre par \'Oui\' ou par \'Non\'',
        'try-again': `Je suis désolé, je n'ai pas compris. Veuillez répondre par \'Oui\' ou par \'Non\'`,
        'max_retries_message': 'Je suis désolé, vous avez atteint le nombre maximum de tentatives de réponse. Si vous rencontrez une urgence médicale, veuillez appeler le 911.',
        'thanks': `Merci d'avoir rempli votre rapport quotidien!`
      },
      'weblink': {
        'intro': 'Veuillez remplir le rapport quotidien de Sara Alert pour'
      }
    },
    'phone': {
      'intro': `Bonjour, voici Sara, l'assistante de santé publique automatisée qui demande votre rapport quotidien.`,
      'try-again': `Je suis désolé, je n'ai pas compris. Essayons encore.`,
      'max_retries_message': 'Je suis désolé, vous avez atteint le nombre maximum de tentatives de réponse. Si vous rencontrez une urgence médicale, veuillez appeler le 911.',
      'thanks': `Merci d'avoir rempli votre rapport quotidien! Au revoir.`,
      'age': 'âge',
      'daily1': ' Il s’agit d’un rapport d’alerte Sara quotidien destiné aux: ',
      'daily2-p': ' Parmi ces personnes ',
      'daily2-s': ' Cette personne est-elle ',
      'daily3': ' y en a-t-il qui présentent un des symptômes suivants ',
      'daily4': ' Veuillez répondre par \'Oui\' ou par \'Non\''
    }
  },
  'so': {
    'symptoms': {
      'cough': {
        'name': 'Qufac',
        'notes': ''
      },
      'difficulty_breathing': {
        'name': 'Neef-qabasho',
        'notes': ''
      },
      'fever': {
        'name': 'Qandho',
        'notes': 'Dareemida xummad ama xaraarad cabbirkeedu yahay ama ka sareysa 100.4°F/38°C'
      },
      'used_a_fever_reducer': {
        'name': 'Isticmaalay Xanuun-baa’bi’iye',
        'notes': '24-kii saac ee la soo dhaafay, ma isticmaashay wax daawo ah oo qanshada baa’bi’isa?'
      },
      'chills': {
        'name': 'Qarqaryo',
        'notes': ''
      },
      'repeated_shaking_with_chills': {
        'name': 'Gariir wata Qarqaryo oo soo noqnoqda',
        'notes': ''
      },
      'muscle_pain': {
        'name': 'Murqo-xanuun',
        'notes': ''
      },
      'headache': {
        'name': 'Madax-xanuun',
        'notes': ''
      },
      'sore_throat': {
        'name': 'Cune-xanuun',
        'notes': ''
      },
      'new_loss_of_taste_or_smell': {
        'name': 'Luminta cusub ee dhadhanka ama urta',
        'notes': ''
      },
      'pulse_ox': {
        'name': 'Aksijiinta Dhiiggaaga',
        'notes': 'Geli cabbirka aksijiinta dhiiggaaga ee ugu hooseeya ee la qaaday 24-kii saac ee la soo dhaafay'
      },
      'fatigue': {
        'name': 'Daal',
        'notes': ''
      },
      'nausea_or_vomiting': {
        'name': 'Lalabbo ama matagid',
        'notes': ''
      },
      'diarrhea': {
        'name': 'Shuban',
        'notes': ''
      },
      'nasal_congestion': {
        'name': 'Nasal Congestion',
        'notes': ''
      },
      'runny_nose': {
        'name': 'Runny Nose',
        'notes': ''
      },
      'temperature': {
        'name': 'Temperature',
        'notes': 'Please enter your current temperature in degrees Fahrenheit'
      },
      'other': {
        'name': 'Other',
        'notes': 'I would like someone to call me to follow-up on other symptoms or additional needs'
      },
      'no_symptoms': 'Astaamo ma laha',
      'new_loss_of_smell': {
        'name': 'ur cusub kaa lunta',
        'notes': ''
      },
      'new_loss_of_taste': {
        'name': 'Dhadhan kaa lunta',
        'notes': ''
      },
      'shortness_of_breath': {
        'name': 'Neef qabatin',
        'notes': ''
      },
      'congestion_or_runny_nose': {
        'name': 'San xidhan ama duuf leh',
        'notes': ''
      }
    },
    'threshold-op': {
      'less-than': 'Ka yar',
      'less-than-or-equal': 'Kayar ama Sinnaansho',
      'greater-than': 'Ka Weyn',
      'greater-than-or-equal': 'Ka Weyn ama Ka siman tahay',
      'equal': 'Loo siman yahay',
      'not-equal': 'Lama sinna'
    },
    'web': {
      'title': 'Warbixinta Maalinlaha ah',
      'bool-title': 'Fadlan xulo dhammaan astaamaha aad dareemayso.',
      'submit': 'Gudbi',
      'thank-you': 'Waad ku mahadsantahay bogida warbixintaada maalinlaha ah!',
      'instruction1': 'If you did not report any symptoms, please continue to follow the recommendations provided by your local health department.',
      'instruction2': 'If you reported any symptoms, your local health department will be reaching out soon. If you have any immediate concerns, please contact your medical provider or local health department. Avoid close contact with other people and stay at home.',
      'instruction3': 'If you are experiencing a medical emergency, please call 911 and let them know you are being monitored by the health department.',
      'instruction4': 'Please use the contact information below to get into contact with a public health official managing your case.',
      'email': 'Email',
      'phone': 'Phone',
      'webpage': 'Webpage'
    },
    'email': {
      'reminder': {
          'subject': 'Xusuusiyaha Sara Alert ee Warbixinta',
          'header': 'Kani waa nidaamka Sara Alert oo ku xusuusinayo inaad fadlan jawaab ka bixiso fariimahayaga warbixinta maalinlaha ah.',
          'dear': 'Gacaliye/Gacaliso',
          'thank-you': 'Waad ku mahadsantahay ka qeyb qaadashada barnaamijka la socoshada Sara Alert. Fadlan buuxi warbixintaada maalinlaha ah adoo adeegsanaya xiriiriyaha hoose.',
          'report': 'Warbixinta Maalinlaha ah',
          'footer': 'Ha ka jawaabin iimaylkan, gudbi iimaylkan, ama wadaag xiriiriyaha. Fariintan waxaa si toos ah u soo saaray nidaamka Sara Alert waana mid gaar ah oo adiga kaliya laguugu talagalay. Haddii aad rabto inaad joojiso helitaanka fariimahan ama aad aaminsan tahay in si khaldan laguugu soo diro, fadlan la xiriir waaxda caafimaadka dadweynaha ee deegaanka. Xogta gaarka ah iyo macluumaad dheeri ah, booqo saraalert.org.'
      },
      'enrollment': {
        'subject': 'Diiwaangelinta Sara Alert',
        'header': 'Ku soo dhowow nidaamka Sara Alert!',
        'dear': 'Gacaliye/Gacaliso',
        'info1': 'Waa lagaa diiwaangeliyay nidaamka la socoshada Sara Alert. Waxaan kaa codsanaynaa inaad bixiso warbixinnada maalinlaha ah ee xaaladaada. Si fudud u guji badhanka hoose oo raac tallaabooyinka shaashada ku yaala.',
        'info2': 'Waxaad heli doontaa xusuusin la mid ah maalin kasta ilaa muddada la socoshadaada ka dhammaato. Haddii aad qabtid wax su’aalo ah, fadlan la xiriir xirfadlaha daryeelka caafimaadka kaasoo kaa caawiyay in lagu diiwaangeliyo.',
        'report': 'Warbixinta Maalinlaha',
        'footer': 'Ha ka jawaabin iimaylkan, gudbi iimaylkan, ama wadaag xiriiriyaha. Fariintan waxaa si toos ah u soo saaray nidaamka Sara Alert waana mid gaar ah oo adiga kaliya laguugu talagalay. Haddii aad rabto inaad joojiso helitaanka fariimahan ama aad aaminsan tahay in si khaldan laguugu soo diro, fadlan la xiriir waaxda caafimaadka dadweynaha ee deegaanka. Xogta gaarka ah iyo macluumaad dheeri ah, booqo saraalert.org.'
      },
      'closed': {
        'subject': 'Warbixintu Sara Alert way dhammaystiran tahay',
        'header': 'Warbixintu Sara Alert way dhammaystiran tahay!',
        'dear': 'Gacaliye/Gacaliso',
        'thank-you': 'La socoshadaada Sara Alert hadda waa la dhammeystiray! Waad ku mahadsantahay ka qeyb qaadashadaada.',
        'footer': 'Ha ka jawaabin iimaylkan, gudbi iimaylkan, ama wadaag xiriiriyaha. Fariintan waxaa si toos ah u soo saaray nidaamka Sara Alert waana mid gaar ah oo adiga kaliya laguugu talagalay. Haddii aad rabto inaad joojiso helitaanka fariimahan ama aad aaminsan tahay in si khaldan laguugu soo diro, fadlan la xiriir waaxda caafimaadka dadweynaha ee deegaanka. Xogta gaarka ah iyo macluumaad dheeri ah, booqo saraalert.org.'
      }
    },
    'sms': {
      'prompt': {
        'intro1': 'Ku soo dhowow nidaamka Sara Alert, waxaan ku soo diri doonnaa warbixinadaada maalinlaha ah ee loogu talagalay',
        'intro2': 'lambarkan telefoon. Xogta gaarka ah iyo macluumaad dheeri ah, booqo saraalert.org.',
        'reminder': 'Kani waa nidaamka Sara Alert oo ku xusuusinayo inaad fadlan jawaab ka bixiso fariimahayaga warbixinta maalinlaha ah.',
        'daily1': 'Tani waa warbixinta maalinlaha ah ee Sara Alert ee loogu talagalay: ',
        'daily2-p': ' Miyuu mid ka mid ah dadkani ',
        'daily2-s': ' Qofkani ma ',
        'daily3': 'wax ka mid ah astaamaha soo socda: ',
        'daily4': ' Ku jawaab \'Haa\' ama \'Maya\'',
        'try-again': 'Waan ka xumahay, maan fahmin. Ku jawaab \'Haa\' ama \'Maya\'',
        'max_retries_message': 'Waan ka xumahay, waxaad gaadhay tirada ugu badan ee isku day jawaab celin ah. Haddii aad la kulanto xaalad caafimaad oo degdeg ah, fadlan wac 911.',
        'thanks': 'Waad ku mahadsan tahay dhammaystirka warbixin maalmeedkaaga!'
      },
      'weblink': {
        'intro': 'Fadlan u buuxi Warbixinta Maalinlaha ee Sara Alert ee'
      }
    },
    'phone': {
      'intro': 'Waa salaaman tahay Sara Alert oo ugu yeeraysa warbixintaada maalinlaha ah.',
      'try-again': 'Waan ka xumahay, maan fahmin. Aan isku dayno markale.',
      'max_retries_message': 'Waan ka xumahay, waxaad gaadhay tirada ugu badan ee isku day jawaab celin ah. Haddii aad la kulanto xaalad caafimaad oo degdeg ah, fadlan wac 911.',
      'thanks': 'Waad ku mahadsan tahay dhammaystirka warbixin maalmeedkaaga! Nabad galyo',
      'age': '',
      'daily1': ' Tani waa warbixinta maalinlaha ah ee Sara Alert ee loogu talagalay: ',
      'daily2-p': ' Miyuu mid ka mid ah dadkani ',
      'daily2-s': ' Qofkani ma ',
      'daily3': ' wax ka mid ah astaamaha soo socda ',
      'daily4': ' Ku jawaab \'Haa\' ama \'Maya\''
    }
  }
};

export {
  mockTranslations
};
